"""Lista dos ícones de interface do Mythverse (tools/icon_gen.py ui). Cada grupo vira folhas de 16 ícones.
id → descrição do desenho (em inglês, para a API de imagens). O id é o que o jogo usa: KT.Icon.html('cmd-attack')."""

UI_GROUPS = {
    # comandos de luta
    'battle': [
        ('cmd-attack', 'ATTACK: two crossed katanas with red-lacquer handles, blades gleaming'),
        ('cmd-defend', 'DEFEND: a round wooden shield with an iron rim held up, a small cream spark on it'),
        ('cmd-guard', 'PARRY: a tower shield with a golden ring flash in front of it, deflecting a blow'),
        ('cmd-ult', 'ULTIMATE: a blazing gold eight-pointed star bursting out of a red seal'),
        ('cmd-allout', 'ALL-OUT ASSAULT: four different blades converging on one point with a red burst in the middle'),
        ('cmd-target', 'TARGET: a red paper talisman with a concentric target ring and a brush-stroke arrow pointing at its center'),
        ('cmd-auto', 'AUTOMATIC: a small wind-up paper crane with a turning brass key on its back'),
        ('cmd-semi', 'SEMI-AUTOMATIC: a paper crane held on an open palm'),
        ('cmd-manual', 'MANUAL COMMAND: a hand holding a war fan (gunbai) pointing forward'),
        ('cmd-speed', 'SPEED: a winged straw sandal trailing three wind strokes'),
        ('cmd-city', 'RETURN TO TOWN: a red torii gate with a curved brush arrow passing back through it'),
        ('cmd-prepare', 'PREPARE: a whetstone sharpening a short blade, sparks flying'),
        ('sp', 'TECHNIQUE POINT: a faceted jade bead glowing teal, tied with a small red cord'),
        ('potion', 'HEALING POTION: a round red gourd bottle with a cork and a paper tag'),
        ('elixir', 'ENERGY ELIXIR: a slim blue porcelain flask with gold sparks rising from it'),
        ('turn', 'TURN ORDER: an hourglass made of bamboo with gold sand'),
    ],
    # efeitos (negativos e positivos)
    'status': [
        ('st-burn', 'BURN: a red-orange flame'),
        ('st-poison', 'POISON: a green drop with a tiny skull inside'),
        ('st-bleed', 'BLEED: three red slash marks with a blood drop'),
        ('st-stun', 'STUN: a yellow spiral with three small stars around it'),
        ('st-freeze', 'FREEZE: a pale blue ice crystal with frost shards'),
        ('st-slow', 'SLOW: a snail carrying a small sand timer on its shell, blue-violet'),
        ('st-armorBreak', 'ARMOR BREAK: a cracked breastplate split by a gold fissure'),
        ('st-mark', 'VULNERABILITY MARK: a pink paper seal with a target circle painted on it'),
        ('st-weaken', 'WEAKEN: a drooping broken sword with a violet downward arrow'),
        ('st-silence', 'SILENCE: a paper talisman pasted over a closed mouth, grey-violet'),
        ('st-atk', 'ATTACK UP: a raised clenched fist wrapped in cloth with an orange upward arrow'),
        ('st-def', 'DEFENSE UP: a blue kite shield with an upward arrow'),
        ('st-spd', 'HASTE: a mint-green feather with speed lines'),
        ('st-crit', 'PRECISION: a golden eye inside a diamond-shaped sight'),
        ('st-critDmg', 'LETHALITY: a dagger piercing a gold skull coin'),
        ('st-dodge', 'EVASION: a swallow in flight leaving an after-image'),
        ('st-lifesteal', 'LIFE STEAL: a white fang with a pink-red drop'),
        ('st-dr', 'BARRIER: a cyan hexagonal crystal barrier'),
        ('st-regen', 'REGENERATION: a green sprout growing from a small heart'),
        ('st-stealth', 'STEALTH: a fox mask half dissolved into grey smoke'),
        ('st-taunt', 'TAUNT: an angry red oni mask shouting'),
        ('st-counter', 'COUNTER STANCE: a sheathed katana with a thumb pushing the guard, a small cream flash'),
        ('st-broken', 'BROKEN GUARD: a shield shattered into pieces with a gold burst'),
        ('st-shield', 'SHIELD: a translucent blue dome over a small paper charm'),
    ],
    # elementos, classes e marcas de fraqueza
    'kind': [
        ('el-fire', 'FIRE element: a red-orange flame emblem'),
        ('el-water', 'WATER element: a blue wave curling into a drop'),
        ('el-nature', 'NATURE element: a green maple leaf with a curled sprout'),
        ('el-earth', 'EARTH element: an ochre mountain rock with a crack of gold'),
        ('el-lightning', 'LIGHTNING element: a violet thunderbolt'),
        ('el-wind', 'WIND element: a mint-green swirl of wind'),
        ('el-ice', 'ICE element: a pale blue snowflake crystal'),
        ('el-light', 'LIGHT element: a warm golden sun disc with short rays'),
        ('el-shadow', 'SHADOW element: a violet crescent moon eclipsing a dark disc'),
        ('cls-vanguarda', 'VANGUARD class: a heavy tower shield with a tassel'),
        ('cls-executor', 'DUELIST class: a single katana drawn halfway from its scabbard'),
        ('cls-arcanista', 'ARCANIST class: a wooden staff topped with a floating orb and paper charms'),
        ('cls-atirador', 'MARKSMAN class: a long asymmetric bow (yumi) with one arrow nocked'),
        ('cls-suporte', 'SUPPORT class: a small bronze prayer bell with a green ribbon and a lotus'),
        ('weak', 'WEAKNESS: a cracked red target ring with a downward gold arrow breaking through it'),
        ('intent', 'ENEMY INTENT: a red oni claw reaching forward with motion strokes'),
    ],
    # navegação e sistema
    'nav': [
        ('nav-journey', 'WORLD MAP: a folded paper map with a red route line and a small torii mark'),
        ('nav-adventure', 'ADVENTURES: a travel banner on a pole with a rolled bedroll'),
        ('nav-party', 'TEAM: four small wooden name tablets hanging in a row, one with a red tassel'),
        ('nav-collection', 'HEROES: a gold summoning star above an open scroll'),
        ('nav-inventory', 'BAG: a cloth travel bag (furoshiki bundle) tied on top'),
        ('nav-ranking', 'RANKING: a three-step wooden podium with a small gold crown on top'),
        ('nav-arena', 'ARENA: two crossed spears behind a round war drum'),
        ('nav-chat', 'CHAT: a paper speech scroll with three brush dots'),
        ('nav-guild', 'GUILD: a tall banner with a crest hanging from a crossbar'),
        ('nav-talents', 'TALENTS: a small bonsai tree whose branches end in glowing beads'),
        ('nav-city', 'TOWN: a two-roof pagoda house with a lit window'),
        ('nav-shop', 'SHOP: a market stall with a striped awning and a hanging coin'),
        ('nav-quests', 'QUESTS: a notice board with a pinned paper and a red seal stamp'),
        ('nav-wiki', 'CODEX: a thick bound book with a ribbon bookmark and a brush'),
        ('nav-menu', 'MENU: a lacquered bento box with four compartments seen from above'),
        ('nav-profile', 'PROFILE: an identity plaque (wooden tablet) with a red hanko seal'),
        ('sys-save', 'SAVE: a paper lantern with a small cloud drawn on it'),
        ('sys-panel', 'SIDE PANEL: a folding screen (byobu) with two panels'),
        ('sys-sound', 'SOUND ON: a small taiko drum with sound strokes'),
        ('sys-mute', 'SOUND OFF: a small taiko drum with a red cross ribbon over it'),
        ('sys-help', 'HELP: a paper lantern with a brush-drawn question curl'),
        ('sys-settings', 'SETTINGS: a brass gear with a small wrench'),
        ('sys-close', 'CLOSE: two crossed brush strokes forming an X, red lacquer'),
        ('sys-back', 'BACK: a curved brush-stroke arrow pointing left'),
        ('sys-lock', 'LOCKED: an old iron padlock, closed'),
        ('sys-unlock', 'UNLOCKED: an old iron padlock, open'),
        ('sys-check', 'DONE: a thick green brush check mark inside a circle'),
        ('sys-alert', 'WARNING: a red paper charm with an exclamation brush stroke'),
        ('sys-gift', 'GIFT: a wrapped present box with a mizuhiki knot'),
        ('sys-mail', 'MAIL: a folded letter tied with a red cord'),
        ('sys-calendar', 'CALENDAR: a hanging paper calendar with one red day'),
        ('sys-clock', 'CLOCK: a round bronze clock with brush-drawn hands'),
    ],
    # recursos
    'res': [
        ('res-gold', 'GOLD: an oval gold koban coin with stamped marks'),
        ('res-crystal', 'CRYSTAL: a faceted sky-blue crystal'),
        ('res-ether', 'ETHER: a small pouch spilling glowing violet dust'),
        ('res-ore', 'TAMAHAGANE STEEL: a rough dark steel ingot with a bright edge'),
        ('res-key', 'SUMMONING KEY: an ornate red-and-gold key with a tassel'),
        ('res-gem', 'GEM: a pink gem cut like a cherry blossom'),
        ('res-star', 'STAR STEEL: a silver ingot with a star glint'),
        ('res-ori', 'ORICHALCUM: a copper-gold ingot glowing orange'),
        ('res-adam', 'ADAMANTITE: a dark green crystal ingot'),
        ('res-shard', 'HERO SHARD: a broken piece of a gold medallion with a star'),
        ('res-xp', 'EXPERIENCE: a small rolled scroll with a rising spark'),
        ('res-energy', 'ENERGY: a gold flame inside a glass orb'),
        ('res-power', 'POWER: a clenched gauntlet holding a small sun'),
        ('res-card', 'CARD: a monster card with a gold border and a fox silhouette'),
        ('res-chest', 'TREASURE: a lacquered chest with gold light escaping the lid'),
        ('res-scroll', 'SCROLL: a rolled paper scroll with a red seal'),
    ],
    # prédios da cidade e tipos de região
    'city': [
        ('b-guild', 'GUILD HALL: a hall with a big crest banner over the door'),
        ('b-dojo', 'DOJO: a training hall with a straw dummy in front'),
        ('b-summon', 'SUMMONING TEMPLE: a small temple with a glowing star above the roof'),
        ('b-shrine', 'SHRINE: a red torii with a stone lantern'),
        ('b-forge', 'FORGE: an anvil with a hammer and a glowing furnace mouth behind'),
        ('b-bank', 'BANK: a strongbox house with a big gold coin emblem'),
        ('b-market', 'MARKET: a balance scale with a coin on one pan'),
        ('b-house', 'TEAM HOUSE: a cosy house with a card album open at the door'),
        ('b-workshop', 'ALCHEMY WORKSHOP: an alembic and a glowing violet flask'),
        ('b-expedition', 'EXPEDITION HOUSE: a compass on top of a backpack'),
        ('b-storage', 'WAREHOUSE: a stack of wooden crates with a tanuki mask sign'),
        ('z-hunt', 'HUNT: a paw print over a pine tree'),
        ('z-dungeon', 'DUNGEON: a stone gate with a dark stairway going down'),
        ('z-boss', 'BOSS: a horned oni skull with a small crown'),
        ('z-rift', 'ABYSSAL RIFT: a violet tear in the air with a spiral inside'),
        ('z-world', 'WORLD INVASION: a dragon head roaring over a globe'),
    ],
    # atributos
    'stat': [
        ('at-hp', 'HEALTH: a red heart held in a leaf'),
        ('at-atk', 'ATTACK: an upright katana with an orange glow'),
        ('at-def', 'DEFENSE: a samurai breastplate'),
        ('at-spd', 'SPEED: a running straw sandal with wind strokes'),
        ('at-crit', 'CRITICAL: an arrow hitting the center of a small target'),
        ('at-critDmg', 'CRITICAL DAMAGE: a cracked skull with a gold gash'),
        ('at-dodge', 'DODGE: a leaf slipping past a spear point'),
        ('at-lifesteal', 'LIFE STEAL: a red bat-wing fang biting a drop'),
        ('at-dr', 'DAMAGE REDUCTION: a layered turtle shell'),
        ('at-regen', 'REGENERATION: a heart with a small green sprout'),
        ('at-healPow', 'HEALING POWER: an open hand with a green glow and a lotus'),
        ('at-dot', 'DAMAGE OVER TIME: a candle dripping purple wax'),
        ('at-boss', 'BOSS DAMAGE: a spear through a horned helmet'),
        ('at-pierce', 'ARMOR PIERCING: an arrow going through a plate of armor'),
        ('at-skill', 'SKILL DAMAGE: an open spell book with a blue flame'),
        ('at-nrg', 'ENERGY GAIN: a gold spark jumping into a glass orb'),
        ('at-cdr', 'TECHNIQUE THRIFT: a jade bead with a small circular arrow around it'),
        ('at-startNrg', 'STARTING ENERGY: a rising sun over a glass orb'),
        ('at-elem', 'ELEMENTAL DAMAGE: a ring of five small colored flames'),
        ('at-breakPow', 'BREAK POWER: a war hammer cracking a stone'),
        ('at-chainPow', 'BOND POWER: two rings linked by a red thread'),
        ('at-thorns', 'THORNS: a round shield covered in spikes'),
        ('at-ultDmg', 'ULTIMATE DAMAGE: a gold star exploding'),
        ('at-luck', 'LUCK: a four-leaf clover on a gold coin'),
    ],
    # diversos (painéis)
    'misc': [
        ('ic-star', 'a five-pointed gold star'),
        ('ic-crown', 'a small gold crown with a red jewel'),
        ('ic-skull', 'a white skull, front view'),
        ('ic-compass', 'a brass travel compass'),
        ('ic-lantern', 'a round paper lantern, lit, with a red band'),
        ('ic-bulb', 'a glowing firefly in a small glass jar (an idea)'),
        ('ic-cards', 'three fanned cards with gold borders'),
        ('ic-target', 'an archery target with one arrow in the center'),
        ('ic-orb', 'a violet crystal orb on a small stand'),
        ('ic-dragon', 'a coiled eastern dragon head, teal'),
        ('ic-rift', 'a violet spiral tear in the air'),
        ('ic-chain', 'three links of a heavy iron chain'),
        ('ic-clones', 'three overlapping silhouettes of the same ninja, fading'),
        ('ic-arrows', 'three arrows flying in parallel'),
        ('ic-heal', 'a green cross made of two leaves'),
        ('ic-fist', 'a clenched fist wrapped in bandages'),
        ('ic-anvil', 'an anvil with a hammer resting on it'),
        ('ic-scale', 'a brass balance scale'),
        ('ic-shield', 'a round shield with an iron boss'),
        ('ic-swords', 'two crossed straight swords'),
        ('ic-bolt', 'a yellow lightning bolt'),
        ('ic-moon', 'a pale crescent moon with one star'),
        ('ic-flame', 'a single orange flame'),
        ('ic-frost', 'a blue snowflake'),
        ('ic-leaf', 'a green leaf'),
        ('ic-rock', 'a grey boulder'),
        ('ic-wave', 'a blue great wave curling'),
        ('ic-vortex', 'a swirling grey-green whirlwind'),
        ('ic-slash', 'a white crescent sword slash'),
        ('ic-beam', 'a straight beam of light crossing diagonally'),
        ('ic-burst', 'a round impact burst with sparks'),
        ('ic-bag', 'a leather satchel with a buckle'),
    ],
}
