"""Itens do Mythverse para tools/icon_gen.py: um ícone pintado por item (bases, míticos e peças de conjunto).

Cada linha: (id da arte, descrição em inglês do objeto). O id da arte é
  b-<id da base>            itens comuns a lendários (src/items.js: bases)
  u-<id do mítico>          itens únicos (uniques)
  s-<id do conjunto>-<espaço>   peças de conjunto (sets: weapon, focus, seal, charm)
A ordem aqui é a ordem das folhas (16 por folha). `python tools/icon_gen.py items --check` confere se todo item do jogo
tem linha aqui (e se não sobrou linha de item que não existe mais).
"""

ITEMS = [
    # ---------------------------------------------------------------- espadas
    ('b-bokken', 'wooden practice sword (bokken) of plain worn oak'),
    ('b-tsuki_katana', 'classic katana with a red-wrapped handle and round guard'),
    ('b-jade_dagger', 'short dagger with a carved green jade blade and gold hilt'),
    ('b-curved_blade', 'old pirate cutlass with a brass basket guard'),
    ('b-temple_nodachi', 'very long nodachi greatsword with a white paper talisman tied to the hilt'),
    ('b-tide_blade', 'wave-shaped curved sword of blue steel with a foam pattern'),
    ('b-frost_blade', 'sword with a pale-blue ice crystal blade and small icicles'),
    ('b-abyss_katana', 'dark navy katana with glowing teal deep-sea runes'),
    ('b-eclipse_blade', 'black sword with a thin glowing crescent edge and an eclipse-ring guard'),
    ('b-dune_scimitar', 'golden desert scimitar with a wide curved blade and a tassel'),
    ('b-ghost_katana', 'translucent pale-green spectral katana trailing mist'),
    ('b-rift_edge', 'jagged sword of purple crystal cracked with violet light'),
    ('b-thunder_tachi', 'tachi sword crackling with yellow lightning, cloud-shaped guard'),
    # ---------------------------------------------------------------- armas pesadas
    ('b-oak_club', 'big knotted oak club with iron studs'),
    ('b-bog_spear', 'muddy swamp spear with reed bindings and dripping moss'),
    ('b-iron_gauntlets', 'a pair of heavy iron fighting gauntlets'),
    ('b-temple_glaive', 'temple naginata glaive with a red tassel'),
    ('b-tide_trident', 'barnacle-covered sea trident with coral and seaweed'),
    ('b-forge_hammer', 'blacksmith war hammer with a glowing ember head'),
    ('b-dune_axe', 'double-headed bronze desert battle axe'),
    ('b-clock_maul', 'giant maul whose head is a clock face with gears'),
    ('b-void_mace', 'black flanged mace with a purple void orb in its core'),
    ('b-bell_maul', 'huge bronze temple bell mounted on a pole as a maul'),
    # ---------------------------------------------------------------- arcos
    ('b-bamboo_bow', 'simple bamboo short bow'),
    ('b-sky_bow', 'sky-blue longbow with a star-tipped arrow'),
    ('b-swamp_sling', 'hunter bow made of twisted reeds and vines'),
    ('b-dusk_bow', 'dark violet bow with a string of shadow thread'),
    ('b-coral_bow', 'bow grown from pink coral with pearl accents'),
    ('b-iron_crossbow', 'heavy iron crossbow with gears'),
    ('b-amber_bow', 'golden amber bow with an arrow trapped inside the amber'),
    ('b-chrono_bow', 'bronze bow with clock hands and small gears'),
    ('b-rift_bow', 'bow of cracked purple crystal with a glowing rift as its string'),
    ('b-tengu_bow', 'red lacquer bow decorated with black tengu feathers'),
    # ---------------------------------------------------------------- cajados e orbes
    ('b-apprentice_staff', 'simple wooden wizard staff with a small blue gem'),
    ('b-firefly_orb', 'glass orb full of glowing fireflies on a small wooden stand'),
    ('b-jade_staff', 'ornate jade staff topped with a dragon head'),
    ('b-veil_scepter', 'silver scepter topped with a crystal of swirling mist'),
    ('b-aurora_scepter', 'scepter with a crystal holding green and pink aurora light'),
    ('b-magma_orb', 'lava orb of dark rock cracked with glowing orange magma'),
    ('b-sun_staff', 'golden staff topped with a radiant sun disc'),
    ('b-specter_orb', 'pale orb with small ghostly souls swirling inside'),
    ('b-rift_scepter', 'dark scepter whose tip pierces a small purple portal'),
    ('b-cloud_staff', 'white staff topped with a small rain cloud'),
    # ---------------------------------------------------------------- relíquias sagradas
    ('b-prayer_bell', 'small golden hand prayer bell with a red cord'),
    ('b-shrine_rosary', 'wooden prayer bead rosary with a tassel'),
    ('b-sacred_staff', 'white priest staff with golden rings at the top'),
    ('b-ice_lily', 'a lily flower made of ice crystal'),
    ('b-censer', 'bronze incense censer hanging on chains, with green healing smoke'),
    ('b-golden_ankh', 'golden ankh'),
    ('b-spectral_harp', 'small ghostly harp with glowing strings'),
    ('b-rift_reliquary', 'ornate reliquary box holding a shard of white light'),
    ('b-hanami_relic', 'a single cherry-blossom petal preserved in a gold-framed crystal'),
    # ---------------------------------------------------------------- tomos e cristais
    ('b-novice_tome', 'plain brown student notebook with a ribbon bookmark'),
    ('b-dull_crystal', 'dull grey cloudy crystal shard'),
    ('b-echo_tome', 'old tome with sound-wave rings embossed on the cover'),
    ('b-memory_crystal', 'clear crystal with faint silhouettes of people inside'),
    ('b-firefly_jar', 'glass jar full of fireflies with a cork lid'),
    ('b-jade_tablet', 'carved green jade tablet with ancient glyph shapes'),
    ('b-aurora_orb', 'orb containing green and pink aurora ribbons'),
    ('b-veil_grimoire', 'grimoire with a misty eye on the cover'),
    ('b-dusk_orb', 'orb pulsing with violet twilight light'),
    ('b-tide_heart', 'heart-shaped blue sea gem with a wave swirl inside'),
    ('b-abyss_crystal', 'dark teal crystal with bioluminescent spots'),
    ('b-eclipse_codex', 'black codex with a silver eclipse ring on the cover'),
    ('b-star_prism', 'triangular glass prism refracting starlight'),
    ('b-sand_hourglass', 'cracked hourglass leaking golden sand'),
    ('b-specter_lantern', 'ghostly paper lantern with a pale-blue flame'),
    ('b-rift_codex', 'forbidden codex bound in chains, with purple runes'),
    ('b-tide_tome', 'sea-blue tome with a shell clasp, salt-stained'),
    ('b-sand_scroll', 'desert papyrus scroll with sand trickling off it'),
    ('b-storm_core', 'crystal core with a lightning bolt trapped inside'),
    ('b-fujin_scroll', 'scroll with green wind swirls and a tassel'),
    # ---------------------------------------------------------------- emblemas
    ('b-recruit_emblem', 'simple iron recruit badge with a single stripe'),
    ('b-fox_banner', 'small war banner with a white fox emblem'),
    ('b-temple_emblem', 'temple guardian medallion with a torii gate symbol'),
    ('b-tide_crest', 'naval crest with an anchor and a wave'),
    ('b-forge_emblem', 'hammered iron insignia with an anvil mark'),
    ('b-pharaoh_banner', 'golden pharaoh war standard with an eye emblem'),
    ('b-clock_crest', 'bronze crest with clock hands pointing upward'),
    ('b-rift_banner', 'torn purple banner woven with glowing threads'),
    ('b-raiju_emblem', 'round emblem scratched by a lightning beast claw'),
    # ---------------------------------------------------------------- aljavas
    ('b-bamboo_quiver', 'bamboo tube quiver with arrows'),
    ('b-hunter_quiver', 'leather hunter quiver with fur trim'),
    ('b-dusk_quiver', 'dark violet quiver with black-feathered arrows'),
    ('b-coral_quiver', 'coral and shell quiver with blue-feathered arrows'),
    ('b-iron_quiver', 'iron-banded quiver holding crossbow bolts'),
    ('b-amber_quiver', 'amber-colored quiver with golden arrows'),
    ('b-chrono_quiver', 'bronze quiver with gears and a clock dial'),
    ('b-rift_quiver', 'quiver with a purple portal at its mouth, arrows emerging'),
    # ---------------------------------------------------------------- selos
    ('b-wood_seal', 'simple wooden charm tag with an ink brush mark'),
    ('b-fox_seal', 'paper seal tag stamped with a red fox mask'),
    ('b-eclipse_seal', 'round seal with a crescent moon symbol'),
    ('b-crimson_seal', 'red lacquer seal plaque with a gold emblem'),
    ('b-moss_seal', 'stone seal covered in green moss'),
    ('b-frost_seal', 'frozen seal plaque covered in frost crystals'),
    ('b-anvil_seal', 'heavy iron seal plate shaped like a small anvil'),
    ('b-tide_seal', 'blue seal with a wave crest and a shell'),
    ('b-shadow_seal', 'black seal tag with a shadow swirl'),
    ('b-star_seal', 'dark blue seal engraved with constellations'),
    ('b-pharaoh_seal', 'golden cartouche seal with hieroglyph shapes'),
    ('b-gear_seal', 'bronze gear-shaped seal'),
    ('b-rift_seal', 'cracked purple seal stitched together with glowing thread'),
    ('b-iron_plate', 'plain iron chest plate'),
    ('b-guard_plate', 'city guard breastplate with a crescent crest'),
    ('b-rift_plate', 'shattered dark armor plate held together by purple energy'),
    ('b-shrine_ward', 'white shrine paper ward with a red seal and two small bells'),
    ('b-cloud_plate', 'granite armor plate with small stone wings'),
    ('b-sakura_ward', 'pink ward charm decorated with cherry blossoms'),
    # ---------------------------------------------------------------- omamoris
    ('b-cloth_omamori', 'simple hand-stitched cloth omamori pouch'),
    ('b-pilgrim_bag', 'small pilgrim travel pouch with a tiny straw hat charm'),
    ('b-luck_omamori', 'golden lucky omamori with a four-leaf clover'),
    ('b-witch_charm', "witch's charm bottle with an eye floating among herbs"),
    ('b-jade_omamori', 'green jade omamori amulet'),
    ('b-snow_omamori', 'white omamori with snowflake embroidery'),
    ('b-sacred_omamori', 'white-and-gold sacred omamori with a sun crest'),
    ('b-sailor_bag', "sailor's canvas pouch with rope and a small anchor"),
    ('b-abyss_omamori', 'dark blue omamori with a glowing anglerfish lure'),
    ('b-celestial_omamori', 'sky-blue omamori woven with clouds and stars'),
    ('b-scarab_charm', 'amber scarab beetle amulet'),
    ('b-ghost_veil', 'delicate translucent white bridal veil charm'),
    ('b-rift_heart', 'pulsing crystal heart, half purple and half gold'),
    ('b-drum_charm', 'tiny taiko drum charm with a triple-comma symbol'),
    # ---------------------------------------------------------------- míticos
    ('u-raijin_drum', "thunder god's ring of taiko drums with triple-comma marks and lightning"),
    ('u-fujin_bag', "wind god's large green bag bursting with wind swirls"),
    ('u-muramasa', 'cursed blood-red katana dripping blood, sinister aura'),
    ('u-kusanagi', 'legendary straight sword wrapped in wind and blades of grass'),
    ('u-star_bow', 'midnight-blue bow studded with a thousand stars'),
    ('u-lunar_edge', 'silver greatsword shaped like a crescent moon'),
    ('u-hagoromo_staff', 'celestial staff draped with a flowing feather-robe ribbon'),
    ('u-celestial_chime', 'golden heavenly wind chime with star-shaped tags'),
    ('u-titan_gauntlets', 'colossal stone-and-gold titan gauntlets'),
    ('u-dragon_fang', 'giant sea-dragon fang blade with a living blue eye on it'),
    ('u-forbidden_tome', 'chained black tome with a red weeping eye'),
    ('u-dragon_eye', 'golden dragon eye orb with a slit pupil'),
    ('u-kitsune_heart', 'heart-shaped orange fox-fire flame with nine small tails'),
    ('u-still_clock', 'stopped pocket watch with frozen hands and cracked glass'),
    ('u-yata_mirror', 'sacred octagonal bronze mirror'),
    ('u-emperor_seal', 'imperial jade seal stamp with a dragon knob'),
    ('u-oni_mask', 'red oni mask with horns and fangs'),
    ('u-phoenix_omamori', 'omamori with a flaming phoenix feather'),
    ('u-temple_bell', 'large bronze temple bell with a wooden striker'),
    ('u-eternal_lantern', 'festival paper lantern with an eternal golden flame'),
    ('u-tide_pearl', 'giant luminous pearl in an open shell'),
    ('u-witch_broom', "witch's broom with hanging charm bottles"),
    ('u-jade_crown', 'ancient cracked jade crown of a dead king'),
    ('u-frost_heart', 'frozen crystal heart of the winter queen'),
    ('u-primordial_hammer', 'massive ancient hammer of dark iron with molten cracks'),
    ('u-sphinx_eye', 'golden sphinx eye amulet with a blue gem'),
    ('u-apep_fang', 'serpent fang dagger dripping green venom'),
    ('u-bride_ring', 'ghostly wedding ring with a pale-blue flame gem'),
    ('u-midnight_bell', 'black clocktower bell with a clock dial at midnight'),
    ('u-rift_shard', 'floating primordial shard of purple-black crystal with a white core'),
    ('u-void_omamori', 'black omamori with a swirling void hole'),
    ('u-frost_fang', 'ice wolf fang blade'),
    ('u-wave_mirror', 'round mirror framed by a breaking wave'),
    ('u-abyss_heart', 'dark heart with glowing purple rift cracks'),
    ('u-ghost_lantern', "ferryman's lantern with a green ghost flame hanging on a hook"),
    ('u-apep_glass', 'hourglass with dark sand, wrapped by a serpent'),
    ('u-sky_chain', 'long iron chain with a hook, a tiny floating island hanging on it'),
    ('u-eternal_petal', 'single glowing cherry petal under a glass bell jar'),
    ('u-cloud_bell', 'small silver bell resting on a cloud'),
    ('u-thunder_crown', 'golden crown crackling with lightning'),
    ('u-ronin_scroll', 'worn ronin scroll with a sword-cut edge and a red seal'),
    # ---------------------------------------------------------------- conjuntos (arma, foco, selo, omamori)
    ('s-grove-weapon', 'wooden guardian staff sprouting green leaves'),
    ('s-grove-focus', 'glowing ancient seed with a sprout'),
    ('s-grove-seal', 'bark armor plate covered in moss'),
    ('s-grove-charm', 'omamori woven from green leaves'),
    ('s-temple-weapon', 'flaming sword with an ember blade'),
    ('s-temple-focus', 'tome with burning ember pages'),
    ('s-temple-seal', 'seal plaque of cooling magma rock'),
    ('s-temple-charm', 'charred smoking omamori with embers'),
    ('s-eclipse-weapon', 'black moon blade with a glowing corona'),
    ('s-eclipse-focus', 'codex with the phases of the moon on its cover'),
    ('s-eclipse-seal', 'seal with a solar eclipse ring'),
    ('s-eclipse-charm', 'dusk-colored omamori, half sun and half moon'),
    ('s-tide-weapon', 'harpoon with a rope and a wave'),
    ('s-tide-focus', 'singing conch shell with a musical swirl'),
    ('s-tide-seal', 'large blue fish-scale armor plate'),
    ('s-tide-charm', 'small pouch overflowing with pearls'),
    ('s-archive-weapon', 'sharp quill pen blade dripping ink'),
    ('s-archive-focus', 'waterlogged tome wrapped in seaweed'),
    ('s-archive-seal', 'stone seal with glowing blue runes'),
    ('s-archive-charm', 'omamori stained with black ink splashes'),
    ('s-dragon-weapon', 'spear made from a sea-dragon fang'),
    ('s-dragon-focus', 'blue dragon eye gem'),
    ('s-dragon-seal', 'dark dragon scale armor plate'),
    ('s-dragon-charm', 'dragon claw holding a glowing pearl'),
    ('s-lantern-weapon', 'folding war fan painted with nine fox tails'),
    ('s-lantern-focus', 'living paper lantern with a fox-fire face'),
    ('s-lantern-seal', 'crimson seal tag with a fox emblem'),
    ('s-lantern-charm', 'festival omamori with tiny hanging lanterns'),
    ('s-swamp-weapon', 'willow wand with a glowing green tip'),
    ('s-swamp-focus', 'tiny bubbling pocket cauldron'),
    ('s-swamp-seal', 'mud-stained paper talisman tag (an object, not an animal) with a green lily pad on it'),
    ('s-swamp-charm', 'herb pouch with dried flowers'),
    ('s-crypt-weapon', 'imperial jade scepter'),
    ('s-crypt-focus', 'square jade imperial stamp'),
    ('s-crypt-seal', 'jade funeral mask'),
    ('s-crypt-charm', 'burial shroud wrap sewn with jade tiles'),
    ('s-frost-weapon', 'blizzard fang ice dagger'),
    ('s-frost-focus', 'giant eternal snowflake crystal'),
    ('s-frost-seal', 'crown made of ice'),
    ('s-frost-charm', 'fur-trimmed cloak glowing with aurora colors'),
    ('s-forge-weapon', 'ancient smith hammer resting on a steel ingot'),
    ('s-forge-focus', 'eternal glowing ember inside a small iron cage'),
    ('s-forge-seal', 'anvil-shaped armor plate'),
    ('s-forge-charm', 'blacksmith leather apron with tools'),
    ('s-sands-weapon', 'golden khopesh sickle-sword'),
    ('s-sands-focus', 'Eye of Horus amulet'),
    ('s-sands-seal', 'royal golden cartouche'),
    ('s-sands-charm', 'sacred blue-and-gold winged scarab'),
    ('s-gladiator-weapon', 'gladius short sword with a laurel sprig'),
    ('s-gladiator-focus', 'arena standard with a crimson flag'),
    ('s-gladiator-seal', 'round gladiator shield'),
    ('s-gladiator-charm', 'golden laurel wreath'),
    ('s-storm-weapon', 'wooden taiko drum mallet (a bachi stick for a drum, not food) wrapped in red cord and crackling with lightning'),
    ('s-storm-focus', 'celestial taiko drum on a cloud'),
    ('s-storm-seal', 'cloud-shaped seal'),
    ('s-storm-charm', 'black tengu feather tied with a red cord'),
    ('s-blossom-weapon', 'folding fan made of cherry petals'),
    ('s-blossom-focus', 'glowing cherry blossom bud'),
    ('s-blossom-seal', 'spring seal with a blossoming branch'),
    ('s-blossom-charm', 'pink flowery omamori'),
    ('s-ghost-weapon', 'elegant ghostly rapier with a ribbon'),
    ('s-ghost-focus', 'haunted hand mirror with a ghost face'),
    ('s-ghost-seal', "bride's brooch with a pale gem"),
    ('s-ghost-charm', 'torn ghostly veil'),
    ('s-clock-weapon', 'giant clock hand used as a sword'),
    ('s-clock-focus', 'glowing coiled mainspring'),
    ('s-clock-seal', 'bronze clock dial used as a shield'),
    ('s-clock-charm', 'winding key on a chain'),
    ('s-abyss-weapon', 'blade that is half steel and half purple portal'),
    ('s-abyss-focus', 'rift eye floating inside a purple crack'),
    ('s-abyss-seal', 'void seal with a small black hole'),
    ('s-abyss-charm', 'shard of a shimmering translucent veil'),
]
