// O Livro do Véu: a história de Tsukimori contada como um livro de fantasia, em capítulos de prosa.
// Cada capítulo se revela quando o jogador chega à região correspondente (unlock). Só texto, sem regra de jogo.
// Formato de cada página: string = parágrafo; { verse:[linhas], by } = canção ou poema; { note } = nota à margem.
(() => {
  const KT = globalThis.KT = globalThis.KT || {};
  const book = [
    {
      id:'prologo', part:'Prólogo', title:'Do lago que refletia a lua',
      epigraph:{ text:'Antes das muralhas houve a água, e antes da água houve a luz que nela dormia.', from:'Primeira linha do Rolo das Guardiãs' },
      pages:[
        'No tempo em que as montanhas ainda não tinham nome e os rios corriam sem saber para onde, havia no fundo de um vale estreito um lago tão quieto que os pássaros o tomavam pelo céu. Nele a lua se deitava todas as noites, inteira e branca, e dizem os velhos que ela se deitava ali mesmo nas noites em que não havia lua alguma no alto. Os primeiros que chegaram ao vale eram pastores cansados de guerra, e ficaram de pé à margem por muito tempo, sem ousar molhar os pés numa água que guardava uma luz que não era sua.',
        'Foi uma menina quem primeiro tocou a superfície. Chamava-se Tsukiko, e a história não guardou o nome de seus pais nem a cor de seus olhos, apenas o que ela disse ao voltar: que por baixo do reflexo não havia fundo, mas uma porta, e que do outro lado da porta havia outras margens, outros lagos, outros céus, cada um com sua própria lua. Os pastores não acreditaram. Então ela ergueu a mão molhada, e a água que escorria de seus dedos não caiu: ficou suspensa no ar como um fio de prata, e o fio ardia.',
        'Àquilo deram o nome de Véu. Não era muro nem janela, mas uma película de luz tecida entre este mundo e todos os demais, fina como a teia que o orvalho revela ao amanhecer e forte como a promessa de quem nada mais possui. Tsukiko aprendeu a costurá-la com lanternas e canções, e ensinou a outras meninas, e estas ensinaram a outras, e assim nasceu a Ordem das Guardiãs do Véu, que por mil e trezentos anos manteve as portas fechadas sem jamais deixar de ouvir o que batia do outro lado.',
        'Em volta do lago ergueu-se Tsukimori, a Floresta da Lua. Primeiro vieram as casas de madeira e o santuário de pedra; depois a forja, porque onde há portas há quem queira arrombá-las; depois o mercado, porque onde há forja há quem precise de pão; e por fim os oito distritos que ainda hoje descem as encostas em degraus de telhado e cerejeira. No centro de tudo ficou a Praça da Lua, e no centro da praça, um medalhão de bronze sobre o qual nenhum pé devia pisar à noite.',
        { verse:['Tece, tece, filha do lago,', 'o fio que a lua esqueceu;', 'o que está fora fica lá fora,', 'o que é teu continua teu.', 'Se alguém bater, não abras ainda,', 'mas guarda o nome de quem bateu:', 'um dia a porta há de abrir-se', 'e quem entrar será dos teus.'], by:'Cantiga de ninar das Guardiãs' },
        'As crianças de Tsukimori aprendem essa cantiga antes de aprender a contar, e poucas percebem que o último verso não é um consolo, mas uma profecia. As Guardiãs sabiam. Por mil e trezentos anos elas guardaram os nomes de todos que bateram no Véu, escritos em rolos de papel de amoreira no fundo do Arquivo, e esperaram pelo dia em que teriam de abrir a porta. Esse dia chegou numa noite de outono, quando a lua se ergueu sobre o lago pela última vez.'
      ]
    },
    {
      id:'noite', part:'Capítulo Primeiro', title:'A noite em que a lua foi tomada',
      epigraph:{ text:'Não houve trovão nem aviso. A luz simplesmente foi-se, como a chama de quem é chamado para longe no meio de uma frase.', from:'Diário de Sayo, última Guardiã'},
      pages:[
        'Sayo tinha dezesseis anos e ainda era a mais nova das Guardiãs quando o Eclipse veio. Naquela noite coubera a ela acender as lanternas do Bosque, tarefa de aprendiz, e ela subia a trilha de pedras com um cesto de pavios no braço e a cabeça cheia de pensamentos que nada tinham a ver com o fim do mundo. Lembrava-se depois de ter parado para amarrar a sandália, e de ter erguido os olhos, e de não ter encontrado a lua onde a deixara.',
        'Em seu lugar pendia um disco negro, perfeitamente redondo, bordejado por um anel de fogo pálido que não aquecia. Não se movia. As estrelas giravam em volta dele como em volta de todas as coisas, mas o disco permanecia no mesmo ponto do céu, fixo como um prego num tampo de mesa. E do lago, que por mil e trezentos anos refletira a lua, subiu uma névoa escura que tinha cheiro de ferro e de cinza de incenso.',
        'Das trilhas vieram os primeiros gritos. Os guardiões de musgo, antigos espíritos do Bosque que por séculos haviam dormido sob as raízes, levantaram-se com os olhos vazios e caminharam na direção da cidade. Raposas feitas de sombra corriam entre as lanternas apagando-as com a língua. E da névoa do lago emergiram formas que não pertenciam a mundo algum: onis de fumaça, autômatos sem dono, cães cujas bocas eram só silêncio.',
        'Quando Sayo desceu correndo ao santuário, encontrou as Guardiãs reunidas em círculo sobre o medalhão da praça, de mãos dadas, cantando a canção de tecer. Doze vozes contra a noite. Ela quis juntar-se a elas e a Guardiã-Mor a deteve com um olhar. "Tu não", disse a velha. "Alguém precisa lembrar." E então o Eclipse inclinou-se sobre a cidade como quem se inclina para soprar uma vela, e as doze vozes calaram-se ao mesmo tempo, e onde elas estavam ficaram apenas doze lanternas no chão, ainda acesas, e depois nem isso.',
        'Por três invernos Sayo guardou Tsukimori sozinha. Aprendeu o que as outras não tiveram tempo de lhe ensinar lendo os rolos do santuário à luz de uma única lanterna, e descobriu neles aquilo que nenhuma Guardiã jamais dissera em voz alta: o Eclipse não era uma coisa só. Quatro senhores o sustentavam, cada um preso a um dos quatro selos que um dia haviam sido postos para contê-los, e que eles mesmos, por razões que os rolos não sabiam dizer, haviam quebrado por dentro.',
        'No quarto inverno, quando a névoa já cobria metade dos distritos e o povo começara a esquecer como era o luar, Sayo fez o que nenhuma Guardiã fizera em treze séculos. Subiu ao medalhão da praça com uma faca de prata, ergueu-a contra o próprio Véu e o rasgou. A ferida abriu-se de cima a baixo com um som de seda antiga, e do outro lado não havia um mundo, mas todos eles ao mesmo tempo, empilhados como páginas de um livro que o vento folheia.',
        'Àquele rasgo chamou-se a Fenda. E pela Fenda, um por um, começaram a atravessar os viajantes.'
      ]
    },
    {
      id:'viajantes', part:'Capítulo Segundo', title:'Os que atravessaram',
      epigraph:{ text:'Ninguém chega à Fenda por acaso. Cada um carrega uma dívida, uma promessa ou uma pergunta, e Tsukimori cobra as três.', from:'Palavras de Sayo aos recém-chegados' },
      pages:[
        'O primeiro a atravessar caiu de joelhos sobre o bronze da praça com uma espada de treino na mão e o rosto sujo de fuligem de outro céu. Não sabia onde estava, nem por quê, nem como voltaria. Sayo lhe estendeu uma tigela de chá e esperou que ele parasse de tremer. Depois lhe disse o nome da cidade, e o nome do inimigo, e que ninguém era obrigado a ficar. Ele ficou. Os que vieram depois também ficaram, e nenhum deles soube explicar por quê.',
        'Vieram guerreiros de montanhas douradas onde o sol nunca se põe inteiro, e pescadores de arquipélagos onde uma dívida se paga com uma viagem. Vieram monges de cidades verticais que treinam subindo escadas sem fim, e máquinas que acordaram sem ordens e escolheram, sozinhas, a gentileza. Vieram irmãos que se odiavam e não conseguiam se separar, velhos ferreiros que acendiam o metal com palavrões, meninas que abriam portas no ar só pelo gosto de chegar atrasadas. Cada um trouxe consigo um pedaço do mundo de onde viera, e Tsukimori, que perdera a lua, começou devagar a encher-se de outras luzes.',
        'Sayo os observava treinar no pátio do Dojo e percebeu uma coisa que os rolos não mencionavam. Quando dois viajantes do mesmo mundo lutavam lado a lado, o Véu ferido reconhecia neles um parentesco antigo e se estendia entre os dois como uma corda que alguém puxa com as duas mãos. Seus golpes se encadeavam. Seus fôlegos se igualavam. Quando um caía, o outro sentia o peso antes de ver a queda. Ao fenômeno ela deu o nome da palavra que sua avó usava para os fios que prendem os barcos ao cais: Kizuna, o laço.',
        { note:'É do Kizuna que nascem as ultimates encadeadas: quando o laço vibra, o golpe de um herói abre caminho para o do outro.' },
        'Assim nasceram as guildas, não de decretos nem de juramentos solenes, mas do medo simples de enfrentar sozinho a próxima coisa que desceria do céu. Duas vezes por dia a Fenda se abria sobre os telhados e algo grande demais para uma equipe só a atravessava, e nessas horas todos os viajantes de Tsukimori subiam às muralhas juntos, os velhos rivais ombro a ombro, e a vida da criatura era dividida entre todos como se divide o pão numa casa pobre. Depois, nas tavernas do Porto, eles contavam a luta em voz alta até que a contassem do mesmo jeito, e então a luta passava a pertencer à cidade.',
        'Sayo nunca lhes disse a parte que mais lhe pesava: que a Fenda não deixava passar apenas heróis. Quanto mais fundo alguém descia por ela, mais antigo e mais faminto era o que encontrava. E que ela, a última Guardiã, abrira a ferida sabendo que talvez nunca conseguisse fechá-la.'
      ]
    },
    {
      id:'shirogane', part:'Capítulo Terceiro', title:'O Rei de Prata sob a Coroa Negra', unlock:{ zone:'hunt' },
      epigraph:{ text:'Há reis que tomam a coroa pela glória, e reis que a aceitam por amor. Destes últimos deves ter mais medo, pois não sabem parar.', from:'Provérbio da dinastia de Jade' },
      pages:[
        'O caminho do primeiro selo começa no Bosque das Lanternas, onde as árvores são tão velhas que as lanternas de papel penduradas em seus galhos já fazem parte da casca. Desde o Eclipse elas atraem criaturas como a chama atrai mariposas, e os guardiões de musgo que antes as protegiam agora vagueiam entre os troncos sem reconhecer ninguém. Os viajantes aprenderam a atravessá-lo em silêncio, e a não responder quando uma voz conhecida os chama pelo nome entre as folhas.',
        'Ao sul do Bosque fica o Pântano dos Vaga-lumes, onde as luzes nunca se apagam e quem as segue à noite não volta. Ali vive a Bruxa do Brejo, que coleciona as vozes dos afogados em potes de barro e as deixa cantar quando se sente sozinha. E por baixo do Pântano dorme a Cripta de Jade, túmulo da dinastia que reinou no vale antes de Tsukimori existir. O Eclipse acordou o último rei, e seus sacerdotes, que nunca souberam que haviam morrido, continuam a servi-lo com a mesma devoção de oito séculos atrás.',
        'Foi nos rolos da Cripta que Sayo encontrou o nome verdadeiro do Rei do Eclipse. Ele se chamava Shirogane, o de Prata, e fora o último Guardião homem da Ordem, séculos antes das regras que excluíram os homens da tecelagem. Tinha uma irmã, Yuzuki, a quem amava mais do que ao Véu, mais do que à cidade, mais do que à própria vida. Quando uma febre que nenhum curandeiro conhecia levou Yuzuki para o outro lado, Shirogane desceu ao Templo do Véu, onde se guardava o primeiro selo, e ali encontrou a Coroa.',
        { verse:['Prata era o nome, e prata a espada,', 'e prata o riso da irmã que partiu;', 'desceu ao templo com a alma quebrada', 'e a coroa negra a ele sorriu.', '"Põe-me na fronte e a verás de novo,', 'um dia, uma hora, um olhar, um só."', 'Ele a pôs. E a lua sobre o povo', 'virou um disco de cinza e pó.'], by:'Balada cantada no Pântano pelas vozes dos potes' },
        'A Coroa não era um objeto, mas uma pergunta com forma de objeto, e a pergunta era sempre a mesma: quanto darias? Shirogane deu seu nome, e ela lhe mostrou a sombra da irmã numa parede. Deu sua memória da infância, e ela lhe mostrou o rosto de Yuzuki num espelho de água. Deu o primeiro selo, que devia guardar, e ela lhe prometeu a voz da irmã. E por fim, quando nada mais lhe restava, deu a lua. A Coroa aceitou. É isso que o Eclipse é: o preço de uma promessa que nunca será cumprida, pendurado no céu para que todos o paguem.',
        'No topo da montanha, sobre o Altar do Eclipse, Shirogane ainda espera. Os que o enfrentaram e voltaram contam que ele não fala com os heróis, mas com alguém que está atrás deles, e que às vezes, no meio da luta, abaixa a espada e escuta. Dizem que quando cai de joelhos, derrotado, sussurra um nome que ninguém entende. E que o primeiro fragmento da lua, quando volta ao céu, brilha por um instante com um tom de prata que nenhum outro fragmento tem.'
      ]
    },
    {
      id:'mizuchi', part:'Capítulo Quarto', title:'O mar que guardava nomes', unlock:{ zone:'hunt_tide' },
      epigraph:{ text:'O mar não esquece. Ele apenas guarda, e devolve quando ninguém mais está esperando.', from:'Dito dos pescadores da Costa das Marés' },
      pages:[
        'Quando o primeiro selo foi restaurado e um fio de prata voltou a correr pelo céu, o mar a leste de Tsukimori estremeceu como um animal que sente mudar o vento. Na manhã seguinte as marés trouxeram de volta os afogados. Não como cadáveres, mas como marinheiros de pé na arrebentação, com a água escorrendo das mangas, esperando ordens. Um capitão sem rosto passeava pela praia recrutando quem se aproximasse, e os que aceitavam deixavam na areia apenas as pegadas de entrada.',
        'A Costa das Marés sempre fora a porta de Tsukimori para o mundo, e por ela chegavam o sal, o arroz e as notícias. Agora chegavam os nomes. Porque o mar, entendeu Sayo, guardava tudo o que nele caía, e o Eclipse não trouxera os afogados de volta por crueldade: trouxera porque alguém lá embaixo estava abrindo as gavetas do fundo, uma por uma, à procura de alguma coisa.',
        'Esse alguém era Mizuchi. Por mil anos o grande dragão das profundezas fora o guardião do Arquivo Submerso, a biblioteca que as primeiras Guardiãs haviam afundado de propósito para que nenhum rei, nenhum ladrão e nenhum Eclipse pudesse ler o que ali estava escrito: a origem do Véu, e o nome de quem o tecera antes de Tsukiko. Mizuchi recebera uma única ordem, gravada em sua escama mais antiga: proteger o Arquivo de quem se aproximasse. O Eclipse não mudou a ordem. Apenas mudou o sentido de uma palavra. Onde estava escrito proteger, o dragão agora lia afogar.',
        'No Arquivo, os escribas continuam a escrever. São espíritos de tinta que nunca souberam fazer outra coisa, e registram em papel que não molha tudo o que acontece no mar e na terra. Mas a tinta ficou envenenada, e as histórias que escrevem agora terminam todas mal. Os viajantes que lá descem aprendem a não ler por cima dos ombros deles, porque às vezes o nome que está sendo escrito é o seu, e a frase ainda não tem ponto final.',
        'Acima da Costa, onde o Eclipse congelou o céu, fica o Planalto Congelado, e ali reina a Rainha do Inverno, que ninguém sabe se é serva ou prisioneira de Mizuchi. Ela guarda o caminho para a Forja Abissal, onde o velho Ren aprendeu o ofício antes de subir para Tsukimori e abrir a forja da cidade. Ren não fala da Forja. Quando perguntam, ele bate o martelo com mais força e diz que há metais que não devem ser acordados, e que os autômatos lá embaixo, que agora forjam armas para o Eclipse, foram um dia seus aprendizes.',
        { verse:['Dorme, dragão, sob a água fria,', 'guarda o que as mães esconderam de nós;', 'nenhuma mão chegará ao teu dia,', 'nenhuma voz além da tua voz.', 'Mas se um dia a lua te faltar,', 'e a ordem antiga virar corrente,', 'lembra que o mar foi feito para dar', 'e não para prender quem o sente.'], by:'Inscrição na porta do Arquivo, lida de cima para baixo' },
        'Os que enfrentaram Mizuchi no Abismo contam que o dragão chora enquanto luta, e que suas lágrimas são água doce no meio do sal. Quando cai, a ordem gravada na escama se apaga, e o mar devolve à costa, numa única maré tranquila, todos os nomes que guardara. As famílias de Tsukimori descem à praia com lanternas para recebê-los. E dos rolos do Arquivo, agora legíveis, sai o nome que ninguém esperava ler: Apep, e o caminho para as Areias onde o tempo escorre.'
      ]
    },
    {
      id:'apep', part:'Capítulo Quinto', title:'A hora devorada', unlock:{ zone:'hunt_desert' },
      epigraph:{ text:'Quem teme a própria hora come as horas dos outros, e nunca se sacia, pois a sua continua lá, esperando.', from:'Inscrição na base da Torre do Relógio' },
      pages:[
        'Além do mar, onde as cartas antigas desenhavam apenas uma mancha amarela e a palavra nada, estende-se o deserto que os viajantes chamam de Areias do Tempo. Ali as horas não passam: escorrem. Um homem pode atravessar uma duna ao meio-dia e chegar ao outro lado com a barba branca, ou dormir uma noite ao pé de uma rocha e acordar menino. As caravanas que ainda cruzam as Areias amarram os camelos uns aos outros com cordas de cânhamo, não por medo de se perderem no espaço, mas no tempo.',
        'Algo enorme se move sob as dunas. Os beduínos das Areias chamam-no de Apep, a Serpente que Engole o Dia, e dizem que ela é tão antiga quanto a primeira ampulheta. Muito antes do Eclipse, um oráculo cujo nome se perdeu viu em sonho a hora exata em que Apep morreria, e escreveu-a numa placa de bronze. A serpente leu a placa. Desde então ela come o tempo. Engole manhãs inteiras, tardes de festa, anos de colheita, qualquer coisa que a afaste daquela hora gravada no bronze, e cada dia devorado é um dia a mais que o mundo deixa de viver.',
        'A leste das dunas ergue-se a Cidade Fantasma, que um dia se chamou Oásis das Mil Fontes. Apep engoliu o tempo dela no meio de um baile, e desde então seus moradores dançam. Os músicos tocam a mesma valsa há duzentos anos. Os noivos trocam o mesmo olhar. Uma criança derruba a mesma taça de vinho, e a taça nunca chega ao chão. Os viajantes que atravessam o salão precisam ter cuidado para não entrar no compasso, porque quem dança três voltas com os mortos não consegue mais parar.',
        { note:'Os moradores da Cidade Fantasma não são maus. Apenas não sabem que a música acabou.' },
        'No centro das Areias fica a Torre do Relógio, que por séculos marcou as horas de todos os mundos que o Véu separa. Suas engrenagens são do tamanho de casas e seus ponteiros medem não minutos, mas destinos. Quem controla a Torre decide quando o Eclipse termina. Por isso Apep enrolou-se em volta dela como um gato em volta de uma tigela, e por isso a Torre agora anda para trás, desfazendo o que os heróis conquistam se eles demorarem demais em seus corredores.',
        'Sayo foi quem entendeu primeiro o que os quatro selos realmente eram. Numa das paredes da Torre, gravado por uma mão que não era humana, havia um desenho dos selos dispostos em cruz sobre o lago de Tsukimori, e embaixo de cada um, uma fechadura. Os selos não prendiam apenas os quatro senhores do Eclipse. Prendiam, todos juntos, alguma coisa que dormia embaixo deles. E a cada selo restaurado, o Eclipse enfraquecia, mas aquela outra coisa se mexia um pouco mais no sono.',
        'No Ninho de Apep, a serpente dorme enrolada na última ampulheta. Se acordar por completo, o tempo deixa de correr em todos os mundos ao mesmo tempo. Os que a venceram dizem que, na hora da queda, ela não resiste: fecha os olhos e espera, como quem ouve enfim um relógio que temia há mil anos, e descobre que o som não era tão terrível assim. A última areia da ampulheta, quando cai, não cai para baixo, mas para cima, e aponta para as nuvens.'
      ]
    },
    {
      id:'raijin', part:'Capítulo Sexto', title:'O tambor sobre as nuvens', unlock:{ zone:'hunt_sky' },
      epigraph:{ text:'Enquanto o tambor soar, o céu não cai. Enquanto o tambor soar, o céu não se cura. Escolhe tu qual das duas dores queres ouvir.', from:'Palavras de Fujin, senhor dos ventos, ao irmão' },
      pages:[
        'Quando Apep caiu, o céu rachou como louça velha. Da rachadura subiram ilhas inteiras, arrancadas do chão com templos, pontes, pomares e aldeias ainda de pé, e ficaram flutuando sobre Tsukimori, presas ao alto por uma força que ninguém entendia. À noite suas sombras passam por cima dos telhados da cidade, e às vezes cai delas uma chuva de pétalas, ou de pedras, ou de peixes que nunca viram o mar.',
        'Lá no alto, onde o ar é fino e as nuvens formam colinas que se pode pisar, fica o Vale das Cerejeiras Eternas, onde é sempre primavera. É o lugar mais belo que os viajantes já viram, e o mais perigoso: as flores têm dentes, os galhos se fecham como mãos, e as pétalas que caem nos ombros de quem passa pesam cada vez mais, até que o viajante se deite para descansar e não se levante nunca. Os que voltam do Vale trazem sempre uma flor presa na roupa, sem lembrar de tê-la colhido.',
        'Acima do Vale ergue-se o Santuário das Nuvens, onde Fujin, o senhor dos ventos, guardava os ventos do mundo em sacos de seda amarrados com cordões de ouro. Fujin se foi, ninguém sabe para onde, e os sacos se romperam. Agora os sinos do Santuário tocam sozinhos, movidos por ventos que não obedecem a ninguém, e cada badalada é um golpe capaz de derrubar um guerreiro de armadura. Os monges que ficaram amarraram-se às colunas com cordas e continuam rezando, embora não saibam mais a quem.',
        'E no topo de tudo, sobre um trono de nuvem negra, está Raijin, o irmão de Fujin, tocando o grande tambor do trovão. Ele não para. Não pode parar. Cada batida sustenta as ilhas no ar, e se o tambor silenciar, tudo o que flutua sobre Tsukimori cairá sobre a cidade como uma segunda noite. Mas cada batida também rasga um pouco mais o Véu, e a Fenda que Sayo abriu com uma faca de prata alarga-se a cada trovão como uma costura que cede.',
        { verse:['Bate, irmão, que o céu é pesado,', 'bate, irmão, que a terra é pequena;', 'se o tambor ficar calado', 'cai a ilha, a flor, a pena.', 'Mas escuta o que diz o vento', 'nas frestas do meu saco rasgado:', 'quem segura o céu por tormento', 'também é por ele esmagado.'], by:'Canção dos monges amarrados às colunas' },
        'Raijin sabe. É isso que torna a luta contra ele tão terrível: ele não é cego como Shirogane nem corrompido como Mizuchi nem medroso como Apep. Ele vê com clareza as duas quedas possíveis e escolheu a sua, e defende essa escolha com toda a fúria de quem carrega sozinho um peso que deveria ser de muitos. Os viajantes que chegam ao Trono precisam fazer o que Raijin não conseguiu: silenciar o trovão sem deixar o céu cair. Para isso é preciso uma guilda inteira, ou uma cidade inteira, erguendo as ilhas com as próprias mãos enquanto o tambor se cala.',
        'Quando o quarto selo se fecha, a lua volta inteira ao céu pela primeira vez em muitos invernos, e por uma noite Tsukimori inteira sai às ruas para olhá-la. Sayo não sai. Ela desce sozinha ao lago, onde a lua outra vez se deita na água, e fica olhando o reflexo por muito tempo. Porque os quatro selos estão fechados, e a Fenda continua aberta, e do fundo dela, pela primeira vez, alguma coisa chamou o seu nome.'
      ]
    },
    {
      id:'fenda', part:'Capítulo Sétimo', title:'O que mora abaixo', unlock:{ zone:'rift' },
      epigraph:{ text:'Não desças pela Fenda para encontrar o fundo. Desce para descobrir quanto de ti resta a cada andar.', from:'Aviso riscado na primeira pedra da descida' },
      pages:[
        'A Fenda Abissal não é uma caverna, embora pareça. Suas paredes são feitas de páginas de mundos que o Véu separou, empilhadas e comprimidas até virarem pedra, e quem encosta a mão nelas sente por um instante o calor de outro sol ou o frio de outro inverno. Cada andar da descida é diferente do anterior, porque cada andar é feito de um mundo diferente, e o vazio que vive entre eles muda de forma para imitar o que encontra.',
        'Os primeiros viajantes que desceram fundo voltaram contando uma coisa que ninguém quis acreditar. Nos andares mais baixos, disseram, havia ruínas de Tsukimori. Não da Tsukimori antiga, mas da de agora: a mesma praça, os mesmos oito distritos, a mesma forja de Ren, só que queimadas, afogadas, cobertas de areia ou despedaçadas pelo trovão. Numa delas, um guerreiro encontrou o próprio corpo, vestido com a sua armadura, caído sobre o medalhão da praça.',
        'Sayo foi quem entendeu. Os andares da Fenda não são ruínas do passado. São futuros que falharam: todas as Tsukimoris que poderiam ter existido se os viajantes tivessem perdido, desistido, escolhido errado ou chegado tarde demais. A Fenda guarda cada um deles como o mar guardava os nomes, e o vazio que vive lá embaixo se alimenta desses futuros e aprende com eles. Aprende a andar como os heróis, a golpear como os heróis, a sorrir como os heróis. Se aprender o bastante, um dia subirá pela Fenda e ninguém saberá distingui-lo de quem atravessou primeiro.',
        'É por isso que os viajantes descem. Não para chegar ao fundo, que talvez não exista, mas para recuperar, andar por andar, as memórias que a Fenda roubou deles na travessia, e para impedir que o vazio aprenda depressa demais. Cada andar vencido é um futuro fechado. Cada recorde gravado na pedra da entrada é uma prova de que, pelo menos naquela vez, Tsukimori não caiu.',
        { note:'Nenhum recorde da Fenda é definitivo. O vazio sempre desce um andar a mais do que o viajante mais fundo.' }
      ]
    },
    {
      id:'kitsune', part:'Interlúdio', title:'A raposa das nove lanternas', unlock:{ zone:'boss_event' },
      epigraph:{ text:'Acende uma lanterna para quem se foi, e ela iluminará teu caminho de volta. Esquece de acendê-la, e ela virá acender-se sozinha.', from:'Costume do Festival das Lanternas' },
      pages:[
        'Uma vez a cada ciclo, quando as ameixeiras florescem fora de época, Tsukimori celebra o Festival das Lanternas. As famílias descem ao lago com lanternas de papel, cada uma com o nome de alguém que partiu escrito em tinta vermelha, e as soltam na água para que atravessem o Véu. Por treze séculos as lanternas partiram. Desde o Eclipse, algumas voltam.',
        'Voltam acesas, navegando contra a corrente, e se juntam na margem sul, onde a névoa é mais densa. Ali, entre elas, desperta a Kitsune das Lanternas, uma raposa de nove caudas feita de fogo e papel, que por séculos guiou as almas pelo Véu e agora não sabe mais para onde levá-las. O Eclipse transformou sua saudade em fome. Ela quer manter acesas as lanternas dos mortos até que alguém se lembre deles, e queima tudo o que se aproxima para que ninguém esqueça.',
        'Os viajantes que a enfrentam aprendem cedo que não se vence a Kitsune com raiva. É preciso lembrar. Durante a luta, os nomes escritos nas lanternas começam a brilhar, e quem os lê em voz alta enfraquece o fogo mais do que qualquer espada. Quando a raposa enfim se aquieta, deita-se no meio das lanternas e adormece, e na manhã seguinte as famílias de Tsukimori encontram na margem nomes que haviam esquecido, avós que ninguém mais visitava, irmãos que partiram tão cedo que nem chegaram a ter rosto na memória de ninguém.',
        'Dizem que a chave que a Kitsune deixa cair ao ser vencida não abre nenhuma porta da cidade. Os mais velhos acham que ela abre a porta de volta, a mesma que Tsukiko encontrou no fundo do lago, e que um dia alguém terá coragem de usá-la.'
      ]
    },
    {
      id:'epilogo', part:'Epílogo', title:'Canção para quem ainda vai chegar', unlock:{ zone:'boss_sky', kill:true },
      epigraph:{ text:'Toda história de Tsukimori termina do mesmo jeito: com alguém à beira do lago, esperando o próximo que vai atravessar.', from:'Última página do diário de Sayo' },
      pages:[
        'Os quatro selos estão fechados e a lua voltou ao céu, mas Sayo ainda não dorme. Ela passa as noites no santuário relendo os rolos das Guardiãs, e descobriu neles, escrita pela mão de Tsukiko, uma frase que nenhuma Guardiã depois dela ousou copiar: que o Véu não foi tecido para separar os mundos, mas para impedir que uma única coisa, muito antiga e muito paciente, passasse de um para outro. Os selos eram as fechaduras. O Eclipse era a chave. E alguém, em algum mundo, ainda a segura.',
        'Ela não sabe quem. Sabe apenas que a voz que a chamou do fundo da Fenda usava a sua própria voz, e que tinha pressa. Por isso, todas as noites, Sayo desce ao lago com uma lanterna acesa e a deixa na margem, voltada para o reflexo da lua. É um convite e um aviso ao mesmo tempo, como a cantiga que as crianças da cidade ainda cantam sem entender o último verso.',
        { verse:['Vem, viajante, por onde o Véu rasga,', 'traz tua dívida, traz tua dor;', 'aqui a lanterna nunca se apaga', 'e o pão se parte seja com quem for.', 'Não te prometo voltar para casa,', 'nem que o fim será o que sonhaste;', 'prometo só esta mesa, esta brasa,', 'e um nome aqui, se um dia o deixaste.'], by:'Canção que Sayo deixa escrita na lanterna da margem' },
        'Esta é a história de Tsukimori até onde ela foi contada. O resto ainda não foi escrito, porque depende de quem atravessa. Cada guilda que se forma, cada Invasão rechaçada, cada andar vencido na Fenda acrescenta uma linha a este livro, e as Guardiãs, se ainda estivessem aqui, diriam que é assim mesmo que deve ser: uma história que só termina quando o último viajante resolver ficar.'
      ]
    }
  ];
  (KT.Lore ||= {}).book = book;
})();
