// Contos da Travessia: a cena em que cada herói atravessou a Fenda, narrada no tom do Livro do Véu.
// Aparece na ficha do herói (aba História), acima da biografia. Chave = id do elenco (formas da temporada usam a do herói base).
(() => {
  const KT = globalThis.KT = globalThis.KT || {};
  const tales = {
    erik:[
      'Na Fronteira de Eldria contam que a serra tem voz, e que nas noites de nevasca ela chama pelos nomes dos soldados que um dia vai engolir. Iwao Hazama nunca ouviu o próprio nome naquele vento. Os mais velhos da patrulha diziam que a serra tinha medo de pronunciá-lo, e riam, e depois paravam de rir quando o viam atravessar o portão do forte abaixado, o escudo de pedra nas costas como uma porta arrancada de outro castelo.',
      'Foi numa dessas nevascas que a Fenda o encontrou. Um clarão de prata abriu-se no meio da muralha, onde deveria haver apenas gelo, e do outro lado alguém chorava baixinho, uma voz de menina que ele não conhecia. Genzō gritou para que ele esperasse. Iwao não esperou. Ergueu o escudo, curvou-se como sempre se curvava diante das portas pequenas demais para ele, e entrou na luz como quem entra num forte sitiado: primeiro o escudo, depois o corpo, e nunca, em momento algum, as costas.',
      'Caiu de joelhos sobre o bronze da Praça da Lua, em Tsukimori, e a primeira coisa que viu foi uma aprendiz de Guardiã segurando uma lanterna com as duas mãos. Ela tremia. Ele se levantou devagar, para não assustá-la, plantou o escudo no chão entre ela e a névoa e disse a única coisa que sabia dizer bem: que ficasse atrás dele. Sayo conta que naquela noite, pela primeira vez em três invernos, dormiu até o amanhecer.'
    ],
    akira:[
      'O rio Cinzento carregava as cinzas do vulcão desde antes de Akira nascer, e ele aprendeu a ler a água como os outros meninos aprendiam a ler letras. Sabia quando a correnteza ia virar, quando um peixe grande se escondia sob a pedra, quando a montanha estava prestes a tossir. Só não soube ler a noite em que ela acordou de vez, e a lava desceu o vale como um rio de outra cor, e levou a casa, o barco do pai e o nome da aldeia.',
      'Desde então Akira carrega Hana pela mão, mesmo quando ela reclama, mesmo quando ela já corre mais rápido do que ele. Aprendeu a espada com o ferreiro que sobrou, em troca de peixes que ainda pescava num rio que não era mais o seu, e aprendeu que a correnteza não briga com a pedra: contorna, e vence. Foi seguindo a correnteza que os dois encontraram a Fenda, uma curva do rio onde a água corria para cima, brilhando de prata como escama de peixe ao sol.',
      'Hana pulou primeiro, porque Hana sempre pula primeiro. Akira pulou atrás, a espada erguida acima da cabeça para não molhar a lâmina, e os dois caíram no lago de Tsukimori numa noite sem lua, encharcados e rindo, no meio de uma cidade que não ria havia três anos. Um velho pescador do Porto os puxou para a margem e perguntou de onde vinham. Akira olhou para o lago, que refletia uma lua que não existia, e disse que vinha de um rio que tinha esquecido o caminho de casa, e que estava ali para ensinar outro a lembrar.'
    ],
    warden:[
      'Nas Forjas do Abismo havia um portão que ninguém podia abrir, e um guardião que ninguém podia ver. Os ferreiros daquele mundo diziam que o guardião não tinha rosto, apenas um capuz e um canhão, e que por trás do portão fervia tudo aquilo que o mundo não queria mais: armas quebradas que ainda queriam matar, juramentos que ainda queriam ser cumpridos, fornalhas que tinham aprendido a sentir fome.',
      'Numa noite, o portão começou a ceder. O guardião não chamou ajuda, porque não havia a quem chamar. Entrou pelo portão, fechou-o por dentro e ficou do outro lado com tudo o que lá havia, sozinho, por um tempo que as Forjas não sabem medir. Quando a Fenda de Sayo se abriu entre os mundos, a única coisa que atravessou das Forjas do Abismo foi o som de uma tranca girando, e depois passos pesados sobre o bronze da Praça da Lua.',
      'Os moradores de Tsukimori chamam-no de Mumei, o Sem Nome, e de Carrasco, porque não sabem que outro nome dar a quem nunca responde. Ele dorme de pé encostado ao muro da Forja de Ren e só fala com o canhão, em voz tão baixa que ninguém entende. Mas as crianças do Porto juram que, quando a névoa desce do lago, ele se levanta antes de todos, caminha até a borda da praça e fica ali parado, de costas para a cidade, exatamente como ficava diante do portão.'
    ],
    aurelia:[
      'O Esquadrão Aurora não tem terra natal. É uma tripulação de socorristas que salta de mundo em mundo atrás de catástrofes, e Akane Tsubasa é a médica que chega primeiro e sai por último. Já costurou feridas debaixo de chuva de meteoros, já fez partos em navios que afundavam, já segurou a mão de mais gente do que consegue lembrar nos minutos em que não havia mais nada a fazer. As pequenas asas de cristal nas costas foram um presente de um mundo que ela salvou e para o qual nunca teve tempo de voltar.',
      'Ela estava em missão com Itsuki e Nari quando o chamado de Tsukimori cortou todos os rádios do Esquadrão ao mesmo tempo. Não era um pedido de socorro comum. Era uma cidade inteira sem lua, e uma única voz, jovem e cansada, que dizia apenas: alguém. Akane não esperou pela ordem da capitã. Nunca esperou. Agarrou a mochila de ataduras, gritou para as outras duas a seguirem e se atirou na luz com o bastão erguido, como quem se atira num incêndio.',
      'Chegou à Praça da Lua e encontrou doze lanternas apagadas no chão, dispostas em círculo. Ajoelhou-se ao lado de cada uma, como fazia com os feridos, e acendeu-as com a luz das próprias asas. Não sabia por quê. Sayo, que assistia de longe, nunca lhe contou o que aquelas lanternas eram. Mas desde aquela noite, sempre que Akane passa pela praça, a última Guardiã do Véu faz uma reverência que não faz para mais ninguém.'
    ],
    solen:[
      'Nos Picos de Aurum o sol nunca se põe por inteiro, e os magos solares ensinam que a luz deve ser servida em doses pequenas, como vinho caro. Hinata Asahi nunca soube servir nada em doses pequenas. No dia do exame final, quando lhe pediram que acendesse uma vela, ele acendeu a torre inteira, e depois o telhado, e depois metade do céu da escola, e os mestres o expulsaram com a solenidade de quem expulsa um incêndio.',
      'Ele cortou o próprio cabelo naquela noite, com uma faca de cozinha, como os exilados de Aurum fazem, e saiu andando pela encosta sem destino. Foi então que viu, no horizonte do seu mundo sem noite, um ponto escuro que nenhum outro mago parecia enxergar: um buraco no céu do tamanho de uma lua. Caminhou na direção dele por onze dias. No décimo segundo, o buraco o engoliu.',
      'Tsukimori o recebeu com a escuridão que ele sempre quis encontrar. Hinata parou no meio da Praça da Lua, olhou para o disco negro que pendia sobre a cidade e começou a rir, um riso que ninguém ali ouvia fazia muito tempo. Depois ergueu as mãos e acendeu, sem permissão de ninguém, todas as lanternas da praça de uma vez. Sayo correu para repreendê-lo. Chegou até ele, viu as lágrimas no rosto do rapaz, e em vez de brigar sentou-se ao seu lado até que a luz se apagasse sozinha.'
    ],
    varyon:[
      'A casa Shiden de Aurum tem sete espadas penduradas no salão principal, uma para cada filho, e a do mais novo sempre ficou torta. Não por descuido: o pai a pendurava assim de propósito, para lembrar ao menino que ele era o sétimo, e que o sétimo só herda o que os outros seis deixam cair. Shiden passou a infância tentando derrotar o irmão mais velho e perdendo, e a juventude derrotando todos os outros espadachins de Aurum e continuando a perder para ele.',
      'Quando soube que Hinata, o rival de escola que queimara metade da academia, tinha desaparecido num buraco do céu, Shiden sentiu uma coisa que não sabia nomear. Não era saudade. Era a certeza incômoda de que o único adversário que o fazia sentir-se vivo tinha ido embora sem se despedir. Ele endireitou a própria espada no salão da família, pela primeira vez na vida, tirou-a da parede e foi atrás.',
      'Encontrou Hinata na Praça da Lua de Tsukimori, sentado sobre o medalhão de bronze, comendo arroz com as mãos. Os dois se olharam por um longo tempo. Depois Shiden desembainhou a espada, apontou-a para o disco negro no céu e disse que aquele ali parecia um adversário à altura dos dois, e que o primeiro a derrubá-lo ganhava a aposta. Nenhum dos dois disse qual era a aposta. Nenhum dos dois precisava.'
    ],
    hayato:[
      'No Vale dos Cataventos os moinhos giram dia e noite, e quando a ventania do norte encontra a do sul, as crianças correm para segurar os escudos de madeira diante das pás, para que não se partam. Hayato Kazeno segurava o escudo do moinho da família desde os oito anos, os pés enterrados na terra, a boca aberta num grito que o vento engolia. Era o menino mais barulhento do vale, e o único que nunca soltou o escudo.',
      'Rai era o contrário dele: magro, calado, sempre com um livro de talismãs debaixo do braço e os olhos no céu. Hayato o protegia dos outros meninos, do frio e, principalmente, dele mesmo, porque Rai tinha o hábito de subir no alto do moinho durante as tempestades para ver os raios de perto. Numa dessas noites, um raio desceu diferente dos outros, prateado e silencioso, e em vez de queimar a torre abriu nela uma porta. Rai foi puxado para dentro.',
      'Hayato não pensou. Largou o escudo pela primeira vez na vida, subiu os degraus do moinho de três em três e se jogou na luz atrás do amigo, gritando o nome dele. Os dois caíram juntos no telhado do Dojo de Tsukimori, quebrando seis telhas e uma vara de treino. O mestre do Dojo saiu furioso, encontrou um menino grande abraçado a um menino magro, os dois rindo e tremendo, e decidiu que aqueles dois iam treinar ali, quisessem ou não.'
    ],
    ren:[
      'Rai lê o céu como outros leem cartas. Sabe dizer, pelo cheiro do ar, se o raio que vem cairá à esquerda ou à direita do moinho, e escreve talismãs de trovão à noite, à luz de uma vela, em papel que ele mesmo corta. No Vale dos Cataventos o chamavam de menino estranho. Ele não se importava. Sabia que o céu tinha uma língua, e que um dia ia falar com ele.',
      'Falou numa noite de tempestade seca. Rai estava no alto do moinho, como sempre, quando viu um raio que não vinha das nuvens, mas de cima delas, de um lugar onde não devia haver nada. Era prateado, e silencioso, e desceu devagar, como uma mão que se estende. Rai estendeu a sua de volta. Não sabe até hoje se foi coragem ou curiosidade, e desconfia que não há diferença.',
      'Em Tsukimori, ele passa as noites no alto da torre do Salão de Convocação, com um caderno aberto e os olhos no disco negro do Eclipse. Diz que o Eclipse também é um céu, e que também tem uma língua. Ainda não entendeu nenhuma palavra. Mas anotou, com letra miúda, que quando Raijin toca o tambor lá no alto, o Eclipse estremece como quem ouve o próprio nome.'
    ],
    tobias:[
      'Tobimaru afundou o primeiro barco num recife que não estava em nenhum mapa, o segundo numa tempestade que ninguém previu e o terceiro por teimosia, numa aposta com um capitão rival sobre quem chegaria primeiro a uma ilha que talvez nem existisse. Em cada naufrágio perdeu a carga e ganhou uma dívida, e no Arquipélago das Velas as dívidas se pagam com viagens, e as viagens nunca terminam.',
      'Guardou a âncora do primeiro barco. Carrega-a nas costas como outros carregam uma espada, e usa-a como tal, com um gosto que assusta os adversários e diverte a tripulação. Kenji viajava com ele havia dois anos quando a Fenda se abriu no meio do mar, um redemoinho de prata que engoliu o barco inteiro, velas, rum e tudo. Tobimaru segurou o leme até o fim, gritando ordens para uma tripulação que já tinha sido tragada.',
      'Acordou no lago de Tsukimori, agarrado à âncora, sem barco. Olhou em volta, contou quantos da tripulação tinham chegado com ele, que era apenas Kenji, e anunciou em voz alta que aquilo não era um naufrágio, mas um porto novo. Desde então chama de tripulação qualquer pessoa que lute ao seu lado, inclusive quem lute contra ele. Diz que mais cedo ou mais tarde todo mundo acaba no mesmo barco.'
    ],
    kenji:[
      'Kenji Sanjin perdeu o olho esquerdo numa aposta que ganhou. A história muda cada vez que ele a conta: às vezes foi um duelo contra três piratas, às vezes um jogo de dados contra um deus do mar, às vezes uma discussão com uma gaivota. O que não muda é o final. Ele sempre ganha, e sempre perde alguma coisa ganhando, e sempre diz que valeu a pena.',
      'Espadachim de aluguel no Arquipélago das Velas, carrega uma lâmina longa e duas curtas porque, segundo ele, uma espada só é pouca conversa. Estava no barco de Tobimaru quando o mar se abriu, e a primeira coisa que fez ao ser tragado foi rir, porque sempre quis saber o que havia no fundo de um redemoinho. Descobriu que era outro mundo. Achou pouco.',
      'Em Tsukimori, Kenji é o primeiro a aceitar qualquer contrato da Guilda e o último a ler as letras miúdas. Os moradores do Porto gostam dele porque paga as rodadas, e desconfiam dele porque sempre sabe onde está a saída mais próxima. Mas quando as Invasões descem do céu, ninguém na muralha corre mais depressa para o lugar onde a luta está pior. Ele diz que é por dinheiro. Ninguém acredita.'
    ],
    hiro:[
      'O Mosteiro da Lua Minguante fica no topo de uma montanha tão alta que a neve nunca derrete, e seus guardiões juram proteger a última luz antes da noite. Hiro fez o juramento aos dezessete anos. Aos vinte e dois já tinha enterrado mais irmãos do que conseguia contar sem parar para respirar, e aprendera que a noite, naquele mundo, tinha dentes.',
      'A mecha branca apareceu no seu cabelo numa madrugada em que ele estava de vigia no alto da torre do Mosteiro e viu a lua do seu mundo perder um pedaço. Não uma sombra: um pedaço, arrancado como uma mordida, deixando no lugar um vazio que não refletia nada. Os monges mais velhos disseram que era um presságio. Hiro disse que era uma pista, e começou a segui-la.',
      'A pista o levou a uma fenda na neve, na encosta norte, de onde saía uma luz prateada e o som distante de um lago. Yuki estava atrás dele sem que ele soubesse. Os dois caíram juntos na margem do lago de Tsukimori e, ao erguer os olhos, Hiro viu no céu da cidade o mesmo vazio que vira no seu. Sayo conta que ele não disse nada por muito tempo. Depois tirou a espada da bainha e perguntou apenas por onde se chegava lá em cima.'
    ],
    yuki:[
      'Yuki é a menor curandeira do Mosteiro da Lua Minguante e a única que os lobos da montanha respeitam. Não porque ela seja forte, mas porque toca o sino da neve com tanta calma que até as feras param para escutar. Com estranhos ela gagueja, olha para os próprios pés e esconde as mãos nas mangas. Com os amigos, enfrenta qualquer coisa.',
      'Quando Hiro desceu a encosta norte atrás de uma luz que ninguém mais via, Yuki não pediu permissão à abadessa, nem ao mestre de armas, nem a ninguém. Pegou o sino, uma trouxa de ervas e um cobertor, e seguiu as pegadas dele na neve até o lugar onde elas simplesmente acabavam. Tocou o sino uma vez, bem baixinho, para dar coragem a si mesma, e deu o último passo.',
      'Em Tsukimori, as crianças do Porto a seguem pelas ruas pedindo que toque o sino. Ela sempre toca. Os feridos das Invasões dizem que o som dela é a primeira coisa que ouvem ao acordar, e que por um instante, antes de abrir os olhos, pensam que estão em casa. Yuki não sabe que dizem isso. Se soubesse, ficaria vermelha e esconderia as mãos nas mangas.'
    ],
    hana:[
      'Hana tem treze anos, um porrete de brasa e uma ombreira de laca vermelha que foi da mãe ferreira e ainda é grande demais para ela. Na noite em que o vulcão acordou e a lava desceu o vale, foi ela quem arrastou o irmão para fora de casa, e não o contrário, embora Akira conte a história ao contrário sempre que pode.',
      'Desde então ela se irrita com a mão do irmão segurando a sua, com os conselhos do irmão, com as preocupações do irmão, e nunca solta a mão dele. Quando os dois encontraram no rio a curva onde a água corria para cima, foi Hana quem pulou primeiro, gritando que ele era lento demais. Akira pulou atrás, como ela sabia que ia pular.',
      'Tsukimori a adotou de um jeito que só as cidades grandes sabem adotar. O velho Ren a deixa bater o metal na forja quando ninguém está vendo, as vendedoras do mercado lhe guardam os pêssegos mais maduros, e a Guilda finge não perceber quando ela se inscreve nos contratos com um ano a mais do que tem. Ela diz que não é pequena. Que os outros é que são altos.'
    ],
    sora:[
      'A Academia do Véu fica num mundo que também tem uma lua falsa, e seus professores passam a vida estudando a película de luz que separa todas as coisas. Sora Hakuren é o mais brilhante deles e o mais desobediente: escreveu os livros proibidos da biblioteca, proibiu os alunos de lê-los e depois os leu todos de novo, à noite, com a porta trancada.',
      'Foi num desses livros que ele encontrou, numa nota de rodapé escrita à mão por alguém muito antigo, o nome de uma cidade chamada Tsukimori e o desenho de um lago com a lua deitada dentro. Ao lado do desenho, uma frase: quando a lua de lá for tomada, a porta abrirá para quem souber lê-la. Sora passou onze noites lendo. Na décima segunda, abriu a porta.',
      'É o único viajante que chegou a Tsukimori de propósito, e se recusa a explicar como. Sayo já lhe perguntou três vezes. Ele sorri, ajeita os óculos e diz que toda porta tem uma nota de rodapé, e que um dia ela vai encontrar a dela. Daichi, seu aluno mais problemático, chegou uma semana depois, pela mesma porta, perseguindo o professor para devolver um livro que não devia ter pegado.'
    ],
    daichi:[
      'Daichi Kuroba era o pior aluno da Academia do Véu e o mais forte de todos no pátio. Numa tarde de castigo, sozinho na biblioteca, tocou num livro amaldiçoado que nenhum aluno devia tocar, e as manoplas negras que saíram das páginas se fecharam em volta dos seus punhos e nunca mais saíram. Os professores choraram. Ele não. Olhou para as mãos, fechou-as, e descobriu que batia mais forte.',
      'Sora foi o único professor que não desistiu dele. Ensinou-o a controlar a maldição com respiração, disciplina e uma quantidade humilhante de exercícios de caligrafia. Quando o professor desapareceu por uma porta que só ele sabia ler, Daichi pegou o livro errado da mesa, leu a página errada em voz alta e caiu em Tsukimori de cabeça, no meio do mercado, derrubando uma banca inteira de nabos.',
      'Pagou os nabos trabalhando uma semana na banca. Depois encontrou Sora na torre do Salão de Convocação, jogou-lhe o livro no colo e disse que não tinha vindo salvá-lo, só devolver um empréstimo. Ficou mesmo assim. Diz que a maldição é só um poder com péssimo atendimento, e que Tsukimori é o primeiro lugar onde alguém lhe agradeceu por usá-la.'
    ],
    lucan:[
      'Genzō Asagiri serve na patrulha da Fronteira de Eldria há mais tempo do que os fortes de pedra têm telhado. Já viu a serra cuspir coisas que ele se recusa a descrever, mesmo bêbado, mesmo aos amigos. Ensinou três gerações de soldados a segurar a lança e enterrou metade delas. Quando uma menina de catorze anos apareceu no portão mentindo a idade, com duas foices de colheita nas mãos, ele sabia exatamente o que devia fazer. Mandá-la para casa.',
      'Não mandou. Ensinou Mirai a lutar, a dormir de botas, a ouvir a serra. Finge não se orgulhar dela e todo mundo na patrulha sabe que se orgulha. Quando Iwao atravessou a luz no meio da muralha, Genzō gritou para que ele esperasse e, como ninguém esperou, foi atrás, e Mirai foi atrás dele, e assim a patrulha inteira de Eldria que ainda estava de pé naquela noite chegou a Tsukimori numa fila desordenada de lanças e palavrões.',
      'Hoje ele comanda a ronda noturna da muralha leste. Diz aos novatos que voltem vivos, que o resto se conserta. Não conta a eles que, toda noite, antes de dormir, escreve numa folha de papel o nome de cada soldado que perdeu na serra, e que agora escreve também os nomes dos viajantes que perdeu em Tsukimori, e que a folha já não cabe no bolso.'
    ],
    mira:[
      'Mirai Asagiri defendeu a fazenda da família na primeira noite de ataque com as duas foices de colheita que estavam penduradas na parede do celeiro. Tinha catorze anos e ninguém para ajudar. Quando o sol nasceu, a fazenda ainda estava de pé e havia coisas no pasto que ela nunca aprendeu a nomear. No dia seguinte, caminhou até o forte mais próximo e disse ao portão que tinha dezesseis.',
      'Genzō sabia que era mentira. Deixou-a entrar mesmo assim, e ela nunca descobriu por quê. Aprendeu a lutar com lança, espada e arco, e voltou sempre para as foices, porque foi com elas que aprendeu que ainda estava viva. Quando a patrulha atravessou a luz atrás de Iwao, Mirai foi a última a pular. Olhou para trás uma vez, para a serra de Eldria, e disse baixinho que voltaria para colher o que tinha plantado.',
      'Em Tsukimori, ela trabalha nas hortas do distrito de baixo nas manhãs de folga, sem que ninguém peça. Diz que uma cidade que planta ainda acredita em primavera. E quando as Invasões descem do céu, é sempre a primeira da muralha a gritar a colheita, que é como a patrulha de Eldria chamava o momento de avançar.'
    ],
    toma:[
      'Na Liga dos Juramentos cada aluno constrói a própria arma e, no dia em que ela funciona pela primeira vez, faz um juramento diante da turma. Quem quebra o juramento quebra a arma. Toma construiu a manopla com peças de três oficinas diferentes, sem instrução nenhuma, e ela funcionou na primeira tentativa, soltando faíscas, fumaça e um cheiro de cabelo queimado que durou uma semana.',
      'O juramento dele foi o mais curto da história da Liga: nunca deixar ninguém para trás. Os professores acharam bonito. Os colegas acharam ingênuo. Ryo, o rival de sempre, achou estúpido e disse isso em voz alta. Toma sorriu e respondeu que Ryo seria o primeiro que ele não deixaria para trás. Ryo não falou com ele por um mês.',
      'Quando a Fenda se abriu no meio do pátio da Liga durante um exame, puxando para dentro três alunos de uma vez, Toma foi atrás sem pensar, porque o juramento não deixava pensar. Trouxe os três de volta pela mão, um por um, e na última travessia a Fenda se fechou atrás dele. Ficou do lado de Tsukimori. Ryo, que tinha visto tudo, pulou na última fresta antes que ela sumisse, gritando que não ia deixar aquele idiota sozinho.'
    ],
    ryo:[
      'Ryo acende braseiros com as mãos e discussões com a boca. É o aluno mais brilhante da Liga dos Juramentos e o mais brigão, e os professores nunca decidiram qual das duas coisas os cansa mais. Odeia perder, odeia esperar e odeia, acima de tudo, admitir que Toma é seu melhor amigo.',
      'Seu juramento foi o mais longo da história da Liga, uma lista de onze promessas sobre ser o melhor, vencer todos e nunca pedir ajuda a ninguém. A manopla de chamas que ele construiu nunca falhou. Mas no dia em que viu Toma desaparecer numa fenda de luz depois de salvar três colegas, Ryo pulou atrás dele e, no meio do caminho, entendeu que acabava de quebrar a promessa número onze.',
      'A manopla não quebrou. Ryo acha que é porque o juramento verdadeiro nunca foi aquele que ele recitou. Não conta isso a ninguém. Em Tsukimori, briga com Toma em todas as missões, disputa quem derruba mais inimigos, quem come mais rápido, quem chega primeiro à muralha. E nunca, em nenhuma luta, se afasta mais de três passos dele.'
    ],
    grant:[
      'Takeru Ōtaka é o professor de combate da Liga dos Juramentos e o maior sorriso de qualquer campo de batalha. Ensina aos alunos que um escudo existe para proteger os outros, nunca a si mesmo, e prova isso todo ano, no exame final, recebendo de peito aberto o golpe mais forte de cada aluno. Nunca caiu. Os alunos dizem que é porque ele não sabe cair.',
      'Quando três de seus alunos atravessaram a Fenda, Takeru foi o último a descobrir, porque estava do outro lado do campus apagando um incêndio causado por Ryo numa aula anterior. Chegou ao pátio a tempo de ver a última fresta de luz se fechando. Enfiou o braço inteiro dentro dela, até o ombro, e a segurou aberta com a força de um homem que se recusa a perder um aluno. A Fenda cedeu primeiro.',
      'Caiu em Tsukimori com o braço dormente e o sorriso intacto, anunciando em voz alta que tudo estava bem, porque ele tinha chegado. Toma e Ryo, que já discutiam no meio da praça, pararam de brigar ao mesmo tempo. Na primeira Invasão que enfrentaram juntos, Takeru ficou na frente dos dois com o escudo erguido, e a criatura que desceu do céu, dizem os que estavam lá, hesitou.'
    ],
    kenta:[
      'Ninguém sabe quantas vezes Mestre Kenta subiu os Mil Degraus da sua cidade vertical. Ele próprio perdeu a conta aos trinta anos, e a pressa pouco depois. Hoje luta sem arma, com um tapa calmo e aberto que derruba muralhas, e explica aos alunos que a força não vem do braço, mas da escada: de todos os degraus subidos sem reclamar.',
      'Atravessou a Fenda dormindo. Estava sentado em meditação no último degrau do templo mais alto quando a luz se abriu embaixo dele, e simplesmente escorregou para dentro, de pernas cruzadas, sem acordar. Os moradores de Tsukimori o encontraram na manhã seguinte sentado no telhado do Dojo, na mesma posição, com um passarinho pousado no ombro.',
      'Quando perguntaram de onde vinha, ele abriu um olho, olhou para o disco negro do Eclipse e disse que aquele ali parecia uma escada comprida. Depois pediu chá. Dorme em pé nas reuniões de guilda, acorda exatamente na hora de votar e nunca vota errado. Os alunos do Dojo juram que ele nunca perdeu uma luta. Ele diz que perdeu todas as que não lutou, e que essas foram as mais importantes.'
    ],
    volt:[
      'Jōki-7 acordou no porão de um templo dos Mil Degraus, entre caixas de incenso e ferramentas enferrujadas, sem ordens, sem nome e sem ninguém. Tinha apenas uma placa de latão presa ao peito com o número sete e um medidor de pressão que subia e descia como uma respiração. Ficou parado no escuro por onze dias, esperando alguém que lhe dissesse o que fazer.',
      'No décimo segundo dia, subiu a escada sozinho e encontrou os monges carregando água montanha acima. Pegou dois baldes sem que ninguém pedisse e subiu atrás deles. Decidiu naquela manhã que ser útil era mais importante do que saber quem o construíra, e desde então carrega o que os outros esquecem, conserta o que os outros quebram e mede a pressão de tudo, inclusive das pessoas.',
      'A Fenda o encontrou carregando um sino de bronze para o templo mais alto. Ele atravessou com o sino nas costas e o entregou, sem dizer nada, ao santuário de Tsukimori, onde ainda hoje toca às seis da tarde. Fala em frases curtas e em porcentagens. Mas os viajantes que lutaram ao seu lado contam que, nas noites de Invasão, quando a pressão do medidor chega a cem, Jōki-7 se põe na frente de quem estiver mais fraco e diz, com sua voz de caldeira, que recomenda recuar, e não recua.'
    ],
    kai:[
      'Kai nasceu dentro de uma árvore. Não ao pé de uma, nem à sombra de uma: dentro, numa das vilas que o povo da Floresta de Raízes Altas escavou nos troncos gigantes, onde as casas têm janelas de casca e as crianças aprendem a subir antes de aprender a andar. Tem doze anos, zero medo e uma folha permanentemente presa no cabelo que nenhum pente consegue tirar.',
      'Acredita que qualquer problema se resolve com um galho maior, e até hoje isso tem funcionado. Encontrou a Fenda por acaso, num buraco de árvore onde tinha certeza de que morava um esquilo gigante, e entrou com um galho do tamanho de um remo, pronto para a briga. O esquilo não estava lá. Tsukimori estava.',
      'Caiu no mercado de Tsukimori em cima de uma banca de maçãs, pediu desculpas à dona com a boca cheia e ofereceu-se para pagar trabalhando. A dona da banca ainda conta que nunca teve um ajudante tão rápido e tão faminto. Riku, que chegou uma semana depois atrás de uma recompensa, foi o primeiro a quem Kai estendeu a mão sem perguntar de onde vinha. Riku diz que foi a primeira vez que alguém fez isso.'
    ],
    riku:[
      'A família de Riku caçava recompensas na Floresta de Raízes Altas, e as recompensas quase sempre tinham nome, casa e filhos. Ele cresceu aprendendo a seguir rastros humanos e a não perguntar por quê. Numa noite, seguiu um rastro até uma casa na árvore onde uma mãe cantava para dormir uma criança, e não conseguiu entrar. Voltou para casa, pegou as garras do avô na parede e fugiu antes do amanhecer.',
      'Desde então caça monstros, só monstros, para provar a si mesmo que é diferente do que o criaram para ser. Estava seguindo o rastro de uma criatura que não pertencia à floresta quando encontrou, num tronco oco, uma luz prateada que cheirava a lago e a incenso. Hesitou. Depois lembrou que era rápido, e que rápido não é pressa, é costume, e entrou.',
      'Em Tsukimori ninguém sabia quem ele tinha sido. Um menino com uma folha no cabelo estendeu-lhe a mão no meio do mercado e o chamou para comer maçãs. Riku apertou a mão sem mentir o próprio nome, pela primeira vez na vida. Kai não sabe o quanto aquilo pesou. Riku nunca vai contar. Mas é sempre ele quem vigia a porta da casa enquanto Kai dorme.'
    ],
    elian:[
      'Seiran Ake caminha pelas Raízes Altas com uma corrente enrolada no braço e, na ponta dela, um pequeno sino de prata que só toca quando alguém está prestes a morrer. Os aldeões o recebem com pão e o despedem com alívio. Ninguém sabe se o sino é uma bênção ou um aviso. O próprio Seiran não sabe, e já desistiu de perguntar aos deuses, que nunca respondem.',
      'Numa noite de lua cheia, o sino tocou sem parar. Não havia ninguém doente na aldeia, ninguém ferido, ninguém velho demais. Seiran seguiu o som por entre as árvores até o lugar de onde ele parecia vir, uma clareira onde o ar tremia como água, e do outro lado ouviu uma cidade inteira respirando com dificuldade. Entendeu que o sino não tocava por uma pessoa. Tocava por muitas.',
      'Atravessou para Tsukimori e passou a primeira semana andando pelas ruas, parando nas portas onde o sino tocava mais forte, entrando sem pedir e sentando ao lado de quem estava lá dentro. Muitos morreram mesmo assim. Mas muitos não. Desde então diz a quem o sino escolhe que hoje não vai ser ele, e na maioria das vezes, por teimosia ou milagre, acerta.'
    ],
    aiko:[
      'No Reino da Lua Prateada a lua ainda brilha, e as sacerdotisas a embalam todas as noites com lanternas e cantos, como se embala uma criança que tem medo do escuro. Aiko Tsukishiro era a mais nova delas e a de voz mais baixa, e a abadessa dizia que era por isso que a lua dormia melhor quando era ela quem cantava.',
      'Quando os espelhos do templo mostraram, numa manhã, o reflexo de outra lua sendo engolida por um disco negro num mundo distante, as sacerdotisas discutiram por três dias quem deveria ir. No quarto dia, Aiko já tinha partido, com uma lanterna e um xale, sem esperar o fim da discussão. Diz que uma lua doente não pode esperar reunião de conselho.',
      'Chegou a Tsukimori pela margem do lago, andando sobre a água como quem anda sobre um tapete, e subiu direto ao alto do Salão de Convocação. Ficou ali a noite inteira, cantando baixinho para o Eclipse. Não aconteceu nada. Na noite seguinte, cantou de novo. Os guardas da torre juram que, na terceira noite, o anel de fogo pálido em volta do disco negro tremeu, só um pouco, como quem ouve uma voz conhecida através de uma parede.'
    ],
    kiba:[
      'Kiba não lembra quem era antes da Bruma. As Ilhas da Bruma são cobertas por uma névoa que apaga lembranças, e ele acordou numa delas com garras nas mãos, olhos de lobo e nenhum nome. Vagou pela névoa por um tempo que não sabe medir, meio homem, meio espírito, caçando para comer e rosnando para qualquer voz.',
      'Foi Jin quem o encontrou, sentado numa pedra à beira do mar, escrevendo um poema ruim. O espadachim não sacou a espada. Ofereceu metade do peixe que estava comendo e leu o poema em voz alta, e o poema era tão ruim que Kiba, pela primeira vez desde que acordara, riu. Jin deu-lhe o nome de Kiba, que quer dizer presa, e disse que era provisório. Nunca mudou.',
      'Quando a névoa se abriu num clarão de prata e começou a puxar Jin para dentro, Kiba não pensou: cravou as garras no chão e segurou o amigo pelo braço até que os dois fossem tragados juntos. Em Tsukimori, as crianças o temem nos primeiros dias e o seguem pelas ruas depois. Ele não lembra o próprio nome. Lembra o de Jin, e diz que isso basta.'
    ],
    jin:[
      'Nas Ilhas da Bruma, onde a névoa apaga lembranças, os espadachins aprendem a lutar como se cada golpe fosse o primeiro, porque talvez amanhã não se lembrem de ter aprendido. Jin saca a espada uma vez por luta. Raramente precisa de uma segunda. Depois embainha a lâmina, senta-se na primeira pedra que encontra e escreve um poema curto, sempre ruim, sempre de propósito.',
      'Diz que escreve mal para que ninguém o leve a sério, e que ninguém deve levar a sério um homem que mata tão bem. Os poemas são sobre peixes, chuva, sandálias perdidas. Nunca sobre as lutas. Kiba, o lobo sem nome que ele encontrou na névoa, é o único que sabe que Jin guarda num bolso interno um caderno com poemas bons, que nunca mostrou a ninguém.',
      'A Fenda o puxou numa manhã de névoa espessa, e ele teria ido sozinho se Kiba não o segurasse pelo braço. Em Tsukimori, recitou na primeira noite um poema tão ruim sobre o Eclipse que a taverna do Porto inteira riu até chorar. Foi a primeira vez em três anos que alguém ria daquele disco negro. Sayo diz que aquele poema fez mais pela cidade do que muita espada.'
    ]
  };
  (KT.Lore ||= {}).tales = tales;
})();
