// Lore do Mythverse: o mundo, os mundos de origem e a história de cada herói.
// Só texto (sem regra de jogo). Aparece na ficha do herói (aba História) e na Enciclopédia.
(() => {
  const KT = globalThis.KT = globalThis.KT || {};

  const world = [
    { title:'Tsukimori, a cidade sob o Véu', text:'Tsukimori nasceu em volta de um lago que refletia a lua mesmo em noites sem lua. Os primeiros moradores descobriram que o reflexo era uma porta: o Véu, uma película de luz que separa este mundo de todos os outros. Por gerações, as Guardiãs do Véu o teceram com lanternas e cantos, e a cidade cresceu em oito distritos entre montanhas, canais e cerejeiras.' },
    { title:'O Eclipse', text:'Há três invernos a lua foi engolida. No lugar dela surgiu o Eclipse, um disco negro que não se move. Com ele vieram criaturas que não pertencem a nenhum mundo: onis de névoa, raposas de sombra, autômatos sem dono. Sayo, a última Guardiã, percebeu que o Eclipse não era uma coisa só: quatro senhores o sustentavam, cada um preso a um selo antigo que eles mesmos quebraram.' },
    { title:'Os quatro selos', text:'Shirogane, o Rei do Eclipse, guarda o primeiro selo no Santuário do Véu. Mizuchi, o Dragão Abissal, afundou o segundo sob a Costa das Marés. Apep, a Serpente do Tempo, enrolou o terceiro nas Areias onde um dia dura um segundo. Raijin, o Tambor do Trovão, rachou o céu para esconder o quarto entre as Ilhas Flutuantes. Cada selo restaurado devolve um pedaço da lua.' },
    { title:'A Fenda', text:'Para lutar, Sayo fez o impensável: rasgou o Véu. A ferida virou a Fenda, um corredor sem fundo por onde heróis de outros mundos atravessam, atraídos por quem precisa deles. Ninguém chega por acaso. Cada viajante carrega uma dívida, uma promessa ou uma pergunta que só Tsukimori pode responder. A Fenda também deixa passar coisas piores, e quanto mais fundo se desce, mais antigo é o que se encontra.' },
    { title:'Os laços', text:'Heróis do mesmo mundo se reconhecem na Fenda como quem ouve o próprio nome numa multidão. Lutando juntos, o Véu os fortalece: é o Kizuna, o laço que dá nome às ultimates em sequência. Sayo acredita que o Eclipse só cai para quem luta junto.' },
    { title:'As Invasões', text:'Duas vezes por dia a Fenda se abre sobre a cidade e algo grande demais para uma equipe atravessa. Nessas horas todos os viajantes de Tsukimori lutam juntos, e a vida da criatura é dividida entre todos. É assim que as guildas nasceram: de gente que não queria enfrentar a próxima Invasão sozinha.' }
  ];

  // Mundos de origem (nome exibido e resumo). A chave é o nome usado no elenco (src/roster.js).
  const worlds = {
    'Picos de Aurum':{ text:'Montanhas douradas onde o sol nunca se põe por completo. Os magos solares e a nobreza de esgrima disputam há séculos quem manda nos picos.' },
    'Vale dos Cataventos':{ text:'Uma vila de moinhos presa entre dois ventos. Todo menino aprende a segurar um escudo contra a ventania; todo estudioso, a ler as tempestades.' },
    'Arquipélago das Velas':{ text:'Mil ilhas ligadas por pontes de corda e barcos. Lá, uma dívida se paga com uma viagem, e uma viagem nunca termina.' },
    'Mosteiro da Lua Minguante':{ text:'Um mosteiro no topo de uma montanha nevada, onde espadachins e curandeiras guardam a última luz antes da noite.' },
    'Aldeia do Rio Cinzento':{ text:'Uma aldeia de ferreiros e pescadores às margens de um rio que carrega cinzas de um vulcão adormecido.' },
    'Academia do Véu':{ text:'A escola onde se estuda o próprio Véu, em outro mundo que também tem uma lua falsa. Professores e alunos desconfiam de tudo, principalmente dos livros.' },
    'Fronteira de Eldria':{ text:'Uma cadeia de fortes de pedra que protege os campos do reino de algo que vive do outro lado da serra. A patrulha nunca dorme inteira.' },
    'Cidade dos Alambiques':{ text:'Uma cidade de vidro e cobre onde tudo se transforma em outra coisa, inclusive os soldados, que trocaram espadas por pólvora e fórmulas.' },
    'Liga dos Juramentos':{ text:'Uma escola de oficinas onde cada aluno constrói a própria arma e faz um juramento diante da turma. Quebrar o juramento é quebrar a arma.' },
    'Cidade dos Mil Degraus':{ text:'Uma cidade vertical de escadarias sem fim. Os monges treinam subindo; os autômatos, carregando o que os monges esquecem.' },
    'Floresta de Raízes Altas':{ text:'Árvores tão grandes que há vilas dentro delas. Crianças aprendem a caçar antes de aprender a ler, e ninguém sabe quem plantou a primeira raiz.' },
    'Reino da Lua Prateada':{ text:'Um reino em que a lua ainda brilha e as sacerdotisas a embalam com lanternas. Quando souberam do Eclipse, mandaram a melhor delas.' },
    'Ilhas da Bruma':{ text:'Ilhas cobertas por uma névoa que apaga lembranças. Espíritos e espadachins vivem lado a lado, e ninguém confia totalmente no próprio passado.' },
    'Valmar':{ text:'Uma república de guildas. Tudo em Valmar tem contrato, carimbo e taxa, até a coragem.' },
    'Estrada dos Dojos':{ text:'Uma estrada de peregrinação com um dojo a cada dia de caminhada. Quem chega ao fim pode desafiar o mestre sem nome.' },
    'Coroa Esmeralda':{ text:'Um império caído onde mercenários e bruxos disputam as ruínas de uma coroa verde que ainda canta à noite.' },
    'Deserto dos Mapas Perdidos':{ text:'Um deserto que muda de forma. Quem desenha o mapa certo encontra cidades inteiras enterradas.' },
    'Terras do Gelo Longo':{ text:'Um inverno que dura gerações. As famílias contam a idade pelo número de invernos que sobreviveram juntas.' },
    'Frota de Órion':{ text:'Uma frota de naves-cidade que perdeu o próprio planeta e vaga entre estrelas protegendo quem sobrou.' },
    'Forjas do Abismo':{ text:'Um mundo em chamas onde carrascos de ferro guardam portões que nunca devem ser abertos.' },
    'Galerias de Sucata':{ text:'Túneis cheios de máquinas quebradas e crianças que as consertam. Tudo explode um pouco, e ninguém acha isso um problema.' },
    'Bosque das Nove Lanternas':{ text:'Um bosque de espíritos-raposa que acendem lanternas para guiar os perdidos, ou para perdê-los de vez.' },
    'Estepes do Vento Solto':{ text:'Planícies sem fim onde o vento carrega conversas de quilômetros. Espadachins andarilhos vivem de duelo em duelo.' },
    'Esquadrão Aurora':{ text:'Não é um lugar: é um esquadrão de resgate que atravessa mundos em crise. Três deles estavam em missão quando a Fenda os puxou.' },
    'Irmandade dos Telhados':{ text:'Uma cidade de telhados colados onde uma irmandade secreta protege os fracos sem que eles saibam.' },
    'Cidade da Névoa Verde':{ text:'Uma cidade tomada por uma névoa doente. Os que sobraram aprenderam a lutar e a curar com o que tinham.' },
    'Planalto dos Coiotes':{ text:'Uma fronteira de ranchos, trens e foras-da-lei, onde a palavra de alguém vale mais que ouro.' },
    'Vale das Runas':{ text:'Um vale onde cada pedra tem uma runa. Ferreiros-magos ensinam aprendizes a acender o metal com palavras.' },
    'Cidadela Autômata':{ text:'Uma cidade de máquinas que acordaram sem saber por quê. Algumas procuram quem as construiu; outras, um motivo para lutar.' },
    'Cidade do Pacto Carmesim':{ text:'Uma cidade onde cada família fez um pacto com um demônio. Os filhos herdam o pacto e decidem o que fazer com ele.' },
    'Selva de Engrenagens':{ text:'Uma selva onde bichos e máquinas cresceram juntos. Caçadores respeitam as duas coisas.' },
    'Arena das Cinzas':{ text:'Um torneio eterno num vulcão. Campeões lutam por nomes que perderam e raramente os recuperam.' }
  };

  // Biografia e fala de cada herói (id do elenco).
  const heroes = {
    solen:{ bio:'Aprendiz de mago solar dos Picos de Aurum, Hinata cortou o próprio cabelo no dia em que foi expulso da escola por "brilhar alto demais". A cicatriz no rosto veio do primeiro feitiço que funcionou. Atravessou a Fenda atrás de uma luz que ninguém mais via, e achou Tsukimori sem lua.', quote:'Se o céu apagou, alguém tem que acender.' },
    varyon:{ bio:'Filho mais novo de uma casa de esgrima de Aurum, Shiden nunca venceu o irmão mais velho, e nunca perdeu para mais ninguém. Chegou a Tsukimori entediado e ficou quando descobriu que Hinata, seu velho rival de escola, também estava lá.', quote:'Levante a guarda. Eu só vou avisar uma vez.' },
    hayato:{ bio:'Hayato segurava o escudo do moinho da família contra a ventania desde os oito anos. É barulhento, come demais e ri de tudo, menos de quem ameaça os amigos. Jurou proteger Rai quando os dois ainda eram crianças, e leva o juramento a sério até hoje.', quote:'Fica atrás de mim. Sempre.' },
    ren:{ bio:'Rai estudava tempestades no Vale dos Cataventos e escrevia talismãs de trovão à noite, sem dormir. Fala pouco e só com quem confia. A Fenda o puxou no meio de um raio, e ele ainda tenta entender se foi acidente.', quote:'Raio não erra. Quem erra é quem não lê o céu.' },
    tobias:{ bio:'Capitão de um barco que afundou três vezes, Tobimaru pagou cada dívida com uma viagem e ficou devendo todas. Carrega a âncora do primeiro barco como arma. Chama todo mundo de "tripulação", inclusive inimigos.', quote:'Âncora ao mar! E quem estiver embaixo que se vire.' },
    kenji:{ bio:'Kenji perdeu o olho numa aposta que ganhou. Espadachim de aluguel no Arquipélago, viajava no barco de Tobimaru até o dia em que os dois caíram juntos na Fenda. Carrega uma lâmina longa e duas curtas porque "uma espada só é pouca conversa".', quote:'Três lâminas. Escolha qual vai te acertar.' },
    hiro:{ bio:'Hiro guarda o Mosteiro da Lua Minguante há poucos anos, mas já enterrou mais irmãos do que gostaria. A mecha branca apareceu na noite em que a lua do seu mundo também começou a sumir. Veio a Tsukimori para descobrir se é o mesmo Eclipse.', quote:'A noite é longa. Eu sou mais.' },
    yuki:{ bio:'A menor curandeira do Mosteiro, Yuki toca o sino da neve para acalmar feridos e assustar lobos. É tímida com estranhos e corajosa com amigos. Seguiu Hiro para a Fenda sem pedir permissão a ninguém.', quote:'Respira. O frio passa. Eu fico.' },
    akira:{ bio:'Filho de pescador, Akira aprendeu a espada com o ferreiro da aldeia em troca de peixe. Protege a irmã mais nova, Hana, desde que o vulcão acordou e levou a casa deles. Conversa com o rio como quem conversa com um amigo velho.', quote:'A correnteza não briga com a pedra. Contorna, e vence.' },
    hana:{ bio:'Hana tem treze anos, um porrete de brasa e nenhuma paciência. Carrega uma ombreira de laca grande demais para ela, herança da mãe ferreira. Acha que o irmão se preocupa demais e está certa.', quote:'Eu não sou pequena. Você que é alto.' },
    sora:{ bio:'Professor da Academia do Véu, Sora estuda portais em livros que ele mesmo proibiu os alunos de ler. Chegou a Tsukimori de propósito, algo que ninguém mais conseguiu, e se recusa a explicar como.', quote:'Toda porta tem uma nota de rodapé.' },
    daichi:{ bio:'Aluno problema da Academia do Véu, Daichi tocou num livro amaldiçoado e ganhou manoplas que não saem. Em vez de chorar, aprendeu a bater mais forte. Sora é o único professor que nunca desistiu dele.', quote:'Maldição é só poder com péssimo atendimento.' },
    lucan:{ bio:'O veterano mais velho da patrulha de Eldria, Genzō já viu a serra cuspir coisas que ele se recusa a descrever. Ensinou Mirai a lutar e ainda finge que não se orgulha dela.', quote:'Volte viva. O resto a gente conserta.' },
    mira:{ bio:'Mirai entrou na patrulha de Eldria aos catorze anos, mentindo a idade. Luta com duas foices de colheita porque foi com elas que defendeu a fazenda da família na primeira noite de ataque.', quote:'Eu colho o que vocês plantaram.' },
    erik:{ bio:'Iwao é tão grande que precisa se abaixar para entrar nos fortes que defende. Fala baixo, anda devagar e nunca recua um passo. Na patrulha dizem que a serra tem medo dele.', quote:'Passe por mim. Se conseguir.' },
    alden:{ bio:'Alquimista da Cidade dos Alambiques, Kōji explode pelo menos um laboratório por semana. Cura melhor do que qualquer médico porque já se queimou de todas as formas possíveis.', quote:'Calma, calma, essa aqui quase nunca explode.' },
    ignis:{ bio:'Coronel da guarda da Cidade dos Alambiques, Homura trocou a espada por uma varinha de pederneira e nunca mais perdeu uma batalha. Severo, pontual e secretamente sentimental, guarda carta de cada soldado que perdeu.', quote:'Formação. Ninguém atira antes da minha ordem.' },
    toma:{ bio:'Toma construiu a própria manopla com peças de três oficinas diferentes e nenhuma instrução. Na Liga dos Juramentos, jurou "nunca deixar ninguém para trás", e agora carrega esse peso literalmente.', quote:'Ela faísca, mas funciona! Quase sempre!' },
    ryo:{ bio:'O aluno mais brilhante e mais brigão da Liga, Ryo acende braseiros com as mãos e com o humor. Odeia perder para Toma e odeia ainda mais admitir que são amigos.', quote:'Explosão controlada é explosão sem graça.' },
    grant:{ bio:'Takeru é o professor de combate da Liga dos Juramentos e o maior sorriso de qualquer campo de batalha. Diz que um escudo existe para proteger os outros, nunca a si mesmo.', quote:'Podem ficar tranquilos: eu cheguei!' },
    kenta:{ bio:'Mestre Kenta subiu os Mil Degraus tantas vezes que perdeu a conta e a pressa. Luta sem arma, com um tapa calmo que derruba muralhas. Dorme em pé nas reuniões de guilda.', quote:'Um golpe. Depois um chá.' },
    volt:{ bio:'Jōki-7 é um autômato a vapor que acordou no porão de um templo dos Mil Degraus. Não sabe quem o construiu e decidiu que ser útil é mais importante que saber. Fala em frases curtas e medidas de pressão.', quote:'Pressão em noventa por cento. Recomendo recuar.' },
    kai:{ bio:'Kai nasceu dentro de uma árvore da Floresta de Raízes Altas e acha que qualquer problema se resolve com um galho grande. Tem doze anos, zero medo e uma folha permanentemente presa no cabelo.', quote:'Achei um galho maior!' },
    riku:{ bio:'Riku veio de uma família de caçadores de recompensa que caçava gente. Fugiu com as garras do avô e agora caça monstros para provar que é diferente. Kai foi o primeiro amigo que ele não mentiu para ter.', quote:'Rápido não é pressa. É costume.' },
    elian:{ bio:'Sacerdote andarilho das Raízes Altas, Seiran carrega uma corrente com um sino que só toca quando alguém está prestes a morrer. Ninguém sabe se é bênção ou aviso, nem ele.', quote:'O sino tocou. Hoje não vai ser você.' },
    aiko:{ bio:'Sacerdotisa do Reino da Lua Prateada, Aiko foi enviada porque é a única capaz de embalar uma lua doente. Fala baixo, sorri pouco e segura a lanterna como quem segura uma criança.', quote:'A lua não morreu. Só está com medo.' },
    kiba:{ bio:'Meio espírito, meio homem, Kiba não lembra quem era antes da Bruma. Luta como um lobo e protege Jin como um irmão, porque foi Jin quem o encontrou perdido na névoa.', quote:'Eu não lembro meu nome. Lembro o seu.' },
    jin:{ bio:'Espadachim errante das Ilhas da Bruma, Jin saca a espada uma vez por luta e raramente precisa de uma segunda. Escreve poemas ruins de propósito, para ninguém levá-lo a sério.', quote:'Uma lâmina. Um corte. Um verso.' },
    drake:{ bio:'Mago de fogo registrado em três guildas de Valmar e expulso de duas. Tatsuya acredita que um dragão vive no próprio braço e não aceita outra explicação.', quote:'Taxa de incêndio? Coloca na conta da guilda.' },
    sienna:{ bio:'Comandante da guilda mais séria de Valmar, Kaede preenche formulários com a mesma disciplina com que segura a alabarda. Adotou Tatsuya como responsabilidade pessoal e se arrepende diariamente.', quote:'Formulário primeiro. Heroísmo depois.' },
    daigo:{ bio:'Daigo percorreu metade da Estrada dos Dojos a pé e a outra metade de joelhos, de tanto apanhar. Hoje é um monge-lutador de punhos em brasa que respeita todo adversário, inclusive os que o derrotaram.', quote:'Levanta. A luta ainda nem começou.' },
    mei:{ bio:'Mei chuta mais alto que qualquer um na Estrada dos Dojos e ri mais alto ainda. Viaja pendurando amuletos de papel de cada dojo que venceu.', quote:'Mais um amuleto para a coleção!' },
    kael:{ bio:'Mercenário cansado da Coroa Esmeralda, Kaito já lutou por todos os lados de uma guerra que não acaba. Continua lutando porque Rina pediu, e ele nunca soube dizer não a ela.', quote:'Eu cobro por hora. Hoje é de graça.' },
    sael:{ bio:'Bruxo de uma asa só, Karasu serviu à coroa verde até ela cair e desde então não serve a ninguém. Frio, elegante e perigoso, atravessou a Fenda procurando algo que perdeu no dia da queda.', quote:'Não me confunda com um aliado. Hoje só temos o mesmo inimigo.' },
    rina:{ bio:'Lutadora e curandeira, Rina cuida de um bar nas ruínas da Coroa Esmeralda e de todo mercenário que entra ferido nele. Bate forte e enfaixa melhor ainda.', quote:'Primeiro eu te curo. Depois a gente conversa sobre a conta.' },
    nadia:{ bio:'Cartógrafa e arqueira, Nanami desenha mapas de um deserto que muda toda noite. Chegou a Tsukimori seguindo um mapa que mostrava uma cidade com uma lua falsa.', quote:'Todo mapa mente um pouco. O meu mente menos.' },
    thorn:{ bio:'Gorō sobreviveu a quarenta invernos do Gelo Longo e perdeu a conta do resto. Resmunga, conta histórias longas demais e quebra montanhas de gelo com uma picareta. Viaja para ensinar o neto, Botan, a voltar para casa sozinho.', quote:'No meu tempo o inverno era mais frio. E eu, mais bonito.' },
    bjorn:{ bio:'Botan é o neto de Gorō e o primeiro xamã da família em cem invernos. Fala com passarinhos, lê runas melhor que o avô e finge não ouvir as histórias dele pela décima vez.', quote:'Vô, você já contou essa. Mas conta de novo.' },
    rook:{ bio:'Comandante de uma nave-cidade da Frota de Órion, Rokurō perdeu a nave, mas não a tripulação. Veio sozinho pela Fenda procurando um lugar onde os seus possam pousar.', quote:'Ninguém fica para trás. Nem aqui.' },
    warden:{ bio:'Ninguém sabe o nome do Carrasco. Guardava um portão nas Forjas do Abismo e o fechou por dentro, com tudo o que havia do outro lado. Fala pouco e só com o canhão.', quote:'...' },
    zara:{ bio:'Suzu cresceu nas Galerias de Sucata consertando tudo com fita e fogo. Seu lançador de foguetes é feito de canos de três vizinhos que ainda não perceberam.', quote:'Se não explodir, não está pronto!' },
    kira:{ bio:'Espírito-raposa do Bosque das Nove Lanternas, Kira guiou viajantes perdidos por séculos, às vezes para casa, às vezes não. Decidiu guiar Tsukimori por curiosidade, e fica por gostar das pessoas.', quote:'Sigam a lanterna. As outras mentem.' },
    haru:{ bio:'Andarilho das Estepes do Vento Solto, Haru vive de duelo em duelo e perde de propósito quando o adversário precisa mais do prêmio. Sorri demais para um espadachim.', quote:'O vento não escolhe lado. Eu escolho.' },
    ivy:{ bio:'Mensageira do Esquadrão Aurora, Itsuki corre tão rápido que às vezes chega antes da mensagem. O medidor no peito conta os segundos que ela ainda pode "pular".', quote:'Já cheguei! Espera, já fui?' },
    nari:{ bio:'Nari tem quinze anos e pilota o menor andador de combate do Esquadrão Aurora, que ela mesma remendou. Leva o trabalho a sério e os adultos, nem tanto.', quote:'Escudo erguido! Todo mundo atrás da lata!' },
    aurelia:{ bio:'Médica de campo do Esquadrão Aurora, Akane já salvou mais vidas do que dormiu noites. As pequenas asas de cristal vieram de um mundo que ela salvou e nunca voltou a visitar.', quote:'Fica comigo. Eu não perco ninguém hoje.' },
    dario:{ bio:'Membro da Irmandade dos Telhados, Daisuke protege uma cidade que nem sabe que ele existe. A cicatriz no olho é de uma noite em que falhou, e ele se lembra dela toda noite.', quote:'Ninguém me viu. É assim que funciona.' },
    cole:{ bio:'Guarda novato da Cidade da Névoa Verde, Kōta estava no primeiro dia de trabalho quando a névoa desceu. Aprendeu a lutar do pior jeito e continua acreditando que dá para salvar todo mundo.', quote:'Primeiro dia e já tô atrasado para o fim do mundo.' },
    dana:{ bio:'Nagi sobreviveu à Névoa Verde misturando ervas, remédios e muita teimosia. Não confia em ninguém de primeira, exceto em Kōta, que lembra alguém que ela perdeu.', quote:'Respira pelo pano. Confia em mim.' },
    wade:{ bio:'Patrulheiro do Planalto dos Coiotes, Watari já foi fora-da-lei, xerife e fora-da-lei de novo. Hoje só quer uma boa história para contar na fogueira.', quote:'Palavra dada é bala gasta. Não desperdiço nenhuma.' },
    garrick:{ bio:'Ferreiro-mago do Vale das Runas, Gantetsu acende o metal com palavras e o humor com palavrões. Ensinou Shiina a abrir portais, e se arrepende só quando ela aparece atrás dele.', quote:'Metal é que nem gente: aquece antes de dobrar.' },
    zira:{ bio:'Aprendiz de Gantetsu, Shiina descobriu sozinha como abrir portais do tamanho de uma porta. Usa isso para chegar atrasada e atacar pelas costas, as duas coisas de propósito.', quote:'Não estava ali. Agora estou aqui.' },
    n9:{ bio:'A Unidade Ômega acordou na Cidadela Autômata com um drone flutuando ao lado e nenhuma ordem. Decidiu que a primeira ordem seria proteger quem não tem ninguém.', quote:'Alvo marcado. Drone pronto. Protocolo: gentileza.' },
    unit7:{ bio:'A Unidade Sigma foi feita para a guerra e odeia isso. Luta com uma espada-serra enorme e pede desculpas a cada inimigo que derruba.', quote:'Desculpa. Desculpa. Ah, desculpa.' },
    rex:{ bio:'Herdeiro de um pacto demoníaco na Cidade do Pacto Carmesim, Raizō decidiu usar o poder para caçar os demônios que o fizeram. Exibido, provocador e irresponsável, mas nunca com a vida dos outros.', quote:'Pacto é pacto. Mas o contrato tem letra miúda.' },
    virel:{ bio:'Irmão gêmeo de Raizō, Yūgen aceitou o pacto por inteiro e se tornou frio como ele. Os dois se odeiam na mesma medida em que não conseguem se abandonar.', quote:'Meu irmão fala. Eu termino.' },
    selene:{ bio:'Bruxa do relógio na Cidade do Pacto Carmesim, Tokiko para o tempo por alguns segundos, sempre no momento mais dramático possível. Considera o próprio estilo uma arma.', quote:'Um segundo, querido. É tudo que eu preciso.' },
    tessa:{ bio:'Caçadora da Selva de Engrenagens, Tsubaki respeita bichos e máquinas por igual. A coruja mecânica no ombro foi a primeira presa que ela decidiu não abater.', quote:'Três flechas. Uma para cada erro seu.' },
    kaji:{ bio:'Campeão da Arena das Cinzas, Kaji luta por um nome que perdeu no primeiro torneio. A máscara esconde o rosto e a corrente em chamas afasta quem pergunta demais.', quote:'Me diga seu nome. Eu esqueci o meu.' },
    kori:{ bio:'Rival eterno de Kaji na Arena das Cinzas, Kori é o gelo contra o fogo dele. Os dois não se falam desde a última final, que terminou empatada por mil anos.', quote:'Fogo apaga. Gelo espera.' }
  };

  KT.Lore = { world, worlds, heroes };
})();
